const LANGUAGE_KEY = "fallenEmpireLanguage";

export const TEXT = {
  en: {
    gameTitle: "Beneath the Throne",
    startSubtitle: "Enter a ruined kingdom through ash, fog, and the road to Ashen Keep.",
    startNote: "New Game begins with a cinematic tutorial, the Ser Kael dragon event, then class selection.",
    heroName: "Hero name",
    newGame: "New Game",
    loadGame: "Load Game",
    language: "Language",
    english: "English",
    spanish: "Español",
    selected: "Selected",
    tutorialBattle: "Tutorial Battle",
    tutorialSub: "Learn combat before the fall of Ashen Keep.",
    goal: "Goal",
    skeletonGoal: "Defeat the skeleton. Use Attack, Potion, and Defend to see what each action does.",
    unchosenSurvivor: "Unchosen survivor",
    roadSkeleton: "Road Skeleton",
    tutorialEnemy: "Tutorial enemy",
    attack: "Attack",
    skills: "Skills",
    skill: "Skill",
    potion: "Potion",
    healthPotion: "Health Potion",
    manaPotion: "Mana Potion",
    defend: "Defend",
    help: "Help",
    skip: "Skip",
    mana: "Mana",
    hp: "HP",
    round: "Round",
    yourTurn: "turn",
    noClass: "You have not chosen a class. Defeat the skeleton first. Your real abilities awaken after the dragon event.",
    notEnoughMana: "Not enough mana.",
    noPotions: "No potions left.",
    noManaPotions: "No mana potions left.",
    manaFull: "Mana is already full.",
    skeletonHit: "Road Skeleton claws",
    heroHits: "attacks for",
    heroPotion: "drinks a potion and restores 35 HP.",
    heroHealthPotion: "drinks a health potion and restores",
    heroManaPotion: "drinks a mana potion and restores",
    heroDefend: "defends. The next hit is reduced.",
    combatBasics: "Combat Basics",
    combatBasicsBody: "Combat is turn-based. Attack deals steady damage, Potion restores HP, Defend reduces the next hit, and class skills unlock after you survive the dragon event.",
    firstVictory: "First Victory",
    firstVictoryBody: "The skeleton collapses. The road falls silent, but Ashen Keep is already burning ahead.",
    continueKeep: "Continue Below the Keep",
    dragonTitle: "The Dragon at Ashen Keep",
    dragonSub: "This is not a normal fight. This is the event that creates your character.",
    survivor: "Survivor",
    diseasedDragon: "Diseased Dragon",
    radiantKnight: "Radiant knight",
    protectedSurvivor: "Protected survivor",
    dragonPortraitText: "Plague-marked dragon",
    barrier: "Barrier",
    nextMoment: "Next Moment",
    wakeKeep: "Wake Below the Keep",
    ashenKeep: "Ashen Keep",
    chooseClass: "Choose Class",
    choosePath: "Choose Your Path",
    pathSub: "The dragon attack leaves you barely alive. A fallen champion shields you long enough to awaken your first class.",
    pathNote: "Each class changes starting stats, starter abilities, and the way your early fights feel.",
    choose: "Choose",
    classNames: {
      warrior: "Warrior",
      rogue: "Rogue",
      mage: "Mage",
      ranger: "Ranger",
      cleric: "Cleric"
    },
    classFlavor: {
      warrior: "A sworn front-line survivor who turns pain into pressure and holds the road when others break.",
      rogue: "A knife in the smoke, built for speed, dirty openings, and punishing enemies before they can answer.",
      mage: "A marked scholar of fire and arcane force, fragile until the battlefield becomes your ritual circle.",
      ranger: "A roadwise hunter who reads tracks, controls distance, and survives where maps stop being honest.",
      cleric: "A keeper of oaths and wards, carrying healing light through ruins that want every flame extinguished."
    },
    mainTutorialTitle: "Tutorial: Cinderhook Slum",
    mainTutorialBody: "You begin in Cinderhook Slum. Use Earn Coin, Clear Alley, Shelter & Ally, Gang Pressure, and the Lower Ward Gate to survive the prologue. NPC cards open supplies, forge work, rest, tavern rumors, Mira, and gang pressure.",
    close: "Close",
    save: "Save",
    load: "Load",
    emptySlot: "Empty Slot",
    damagedSave: "Damaged Save",
    noSave: "No save in that slot.",
    home: "Home",
    town: "Town",
    gear: "Gear",
    party: "Party",
    companion: "Companion",
    progression: "Progression",
    stats: "Stats",
    classes: "Classes",
    weapons: "Weapons",
    mastery: "Mastery",
    abilityBook: "Ability Book",
    knownAbilities: "Known Abilities",
    activeAbilitySlots: "Active Ability Slots",
    activeInCombat: "Only active abilities appear in combat.",
    slot: "Slot",
    equip: "Equip",
    unequip: "Unequip",
    active: "Active",
    emptyAbilitySlot: "Empty ability slot.",
    noActiveAbilities: "No active abilities equipped.",
    abilityNotActive: "That ability is not equipped.",
    abilityCost: "Mana cost",
    abilityMilestone: "Ability Milestone",
    chooseNewAbility: "Choose one new ability for your Ability Book.",
    learnAbility: "Learn",
    learnedAbility: "Learned ability",
    currentClass: "Current Class",
    activeClass: "Active",
    baseClass: "Base Class",
    classPath: "Class Path",
    classPaths: "Class Paths",
    baseClassPathBody: "Your original training remains available.",
    unlockClass: "Unlock Class",
    switchClass: "Switch Class",
    classUnlocked: "Class unlocked",
    classChanged: "Class changed",
    unlocked: "Unlocked",
    locked: "Locked",
    available: "Available",
    requiresLevel: "Requires level",
    weaponMastery: "Weapon Mastery",
    spellMastery: "Spell Mastery",
    currentWeapon: "Current Weapon",
    weaponType: "Weapon Type",
    critBonus: "Crit",
    damageBonus: "Damage",
    spellDamage: "Spell",
    healingBonus: "Healing",
    classMastery: "Class Mastery",
    cmAllocation: "Class Mastery XP Allocation",
    cmAllocationHelp: "Choose how much earned battle XP becomes Class Mastery XP instead of normal level XP.",
    cmXp: "CM XP",
    cmPoints: "CM Points",
    cmSpent: "Spent CM",
    cmNextPoint: "Next CM Point",
    cmAvailable: "Available",
    cmPurchased: "Purchased",
    cmLocked: "Locked",
    cmCost: "Cost",
    cmRequires: "Requires",
    cmRequiresLevel: "Requires level",
    cmRequiresSpent: "Requires spent CM",
    cmRequiresNode: "Requires mastery",
    cmNoNodes: "No class mastery nodes for this class.",
    cmBranches: {
      Vanguard: "Vanguard",
      Breaker: "Breaker",
      Bulwark: "Bulwark",
      Knives: "Knives",
      Shadows: "Shadows",
      Arcane: "Arcane",
      Elemental: "Elemental",
      Marksman: "Marksman",
      Wilds: "Wilds",
      Restoration: "Restoration",
      Warding: "Warding",
      Judgment: "Judgment",
      Path: "Path",
      Signature: "Signature",
      Capstone: "Capstone"
    },
    cmNotEnoughPoints: "Need more Class Mastery points.",
    cmMasteryBought: "Mastery learned",
    normalXp: "Normal XP",
    classMasteryXp: "Class Mastery XP",
    xpSplit: "XP Split",
    boughtStatus: "Bought",
    map: "Map",
    kingdoms: "Kingdoms",
    currentLocation: "Current Location",
    openMap: "Open Map",
    overworldMap: "Overworld Map",
    overworldHelp: "Choose a connected location on the map. Your marker follows the road; travel may be interrupted.",
    mapActivity: "Map Activity",
    mapEntityCaravan: "Merchant caravan",
    mapEntityPatrol: "Road patrol",
    mapEntityMonster: "Roaming monster",
    mapEntityAdventurer: "Wandering adventurer",
    mapEventCampfire: "Campfire",
    mapEventCrashedCaravan: "Crashed caravan",
    mapEventStrangeGlow: "Strange magical glow",
    mapEventBurningVillage: "Burning village marker",
    mapEventMonsterNest: "Monster nest",
    mapEventTravelingMerchant: "Traveling merchant",
    playerMarker: "Player marker",
    travelingTo: "Traveling to",
    travelInProgress: "Travel in progress",
    travelAmbush: "Ambush!",
    travelAmbushBody: "Something moves in the ash...",
    travelStrangeEvent: "Strange Road Sign",
    travelStrangeEventBody: "The road bends through old smoke and whispers before settling again.",
    travelMerchantEvent: "Roadside Trader",
    travelMerchantEventBody: "A wary traveler shares supplies before vanishing into the ash.",
    travelDiscoveryEvent: "Road Discovery",
    travelDiscoveryEventBody: "You find a half-buried cache near the road.",
    travelRoadStop: "Road stop",
    currentRoadStop: "Current Road Stop",
    destination: "Destination",
    journeyProgress: "Journey Progress",
    roadCondition: "Road Condition",
    roadConditionUncertain: "Uncertain",
    roadStopDefaultDesc: "The road quiets for a moment, though the ash never fully settles.",
    continueJourney: "Continue Journey",
    inspectArea: "Inspect Area",
    turnBack: "Turn Back",
    turnBackDisabled: "Turn Back is only available at road stops after leaving the origin.",
    journeyNotReady: "You are not stopped on the road.",
    roadStopAlreadyInspected: "You have already searched this stop.",
    roadStopInspectFound: "You uncover a small cache near the road.",
    roadStopInspectQuiet: "You find tracks and cold ash, but nothing useful.",
    roadStopAfterBattle: "The road is yours again. The ash settles around the fallen.",
    forceTravelEncounterReady: "Next travel segment will force an encounter.",
    travelingBetweenRoadStops: "Traveling between road stops.",
    noServicesOnRoad: "No services available on this road.",
    establishCamp: "Establish Camp",
    futureSystem: "Future System",
    cannotBuildHere: "Cannot build here",
    controlledTerritory: "Controlled territory",
    dangerousRoad: "Dangerous road",
    tooCloseToTown: "Too close to town walls",
    nearbyThreats: "Nearby threats",
    strategicValue: "Strategic value",
    cancelTravel: "Cancel Travel",
    alreadyTraveling: "Already traveling.",
    travelCanceled: "Travel canceled.",
    enterLocation: "Location",
    routes: "Routes",
    localActions: "Local Actions",
    localActionsHelp: "Scout for small finds or hunt when you want a nearby battle.",
    services: "Services",
    locationServices: "Location Services",
    noServicesHere: "No services are available here.",
    serviceUnavailable: "That service is not available at this location.",
    travelTo: "Travel to",
    returnTo: "Return to",
    backToLocation: "Back to Location",
    huntNearby: "Hunt Nearby",
    scoutNearby: "Scout Nearby",
    hardAreas: "Hard Areas",
    hardAreasHelp: "High-risk fights with stronger enemy groups and better rewards. These are meant to test builds, companions, potions, and class mastery.",
    enterHardArea: "Enter Hard Area",
    hardAreaLocked: "That hard area is not available from here.",
    hardAreaStarted: "Hard area entered",
    hardAreaCleared: "Hard area cleared",
    recommendedLevel: "Recommended Lv",
    enemyCount: "Enemies",
    highRisk: "High Risk",
    cleared: "Cleared",
    attempts: "Attempts",
    danger: "Danger",
    unknownLocation: "Unknown location.",
    routeLocked: "No route from here.",
    connectedRoutes: "Connected Routes",
    travelFromMapHelp: "Tap a connected node on the map or use a route below to travel.",
    noPreviousLocation: "No previous location.",
    travelEncounter: "Road Encounter",
    travelResource: "Travel Find",
    arrivedAt: "Arrived at",
    scoutEncounter: "Scout Encounter",
    scoutFind: "Scout Find",
    worldMap: "World Routes",
    worldMapBody: "Use the map for overworld routes, connected locations, and guided travel. Local buildings and actions live on the current-location screen.",
    kingdomWorldBody: "Kingdom pressure is still tracked by region. Later passes will bind wars and settlements to specific world nodes.",
    kingdomLocation: "Regional foothold",
    combat: "Combat",
    enemies: "Enemies",
    battleLog: "Battle Log",
    turnOrder: "Turn Order",
    explore: "Explore",
    hunt: "Dangerous Hunt",
    boss: "Regional Boss",
    rest: "Rest",
    camp: "Camp",
    run: "Run",
    auto: "Fight Bot",
    victory: "Victory Rewards",
    defeat: "Defeat",
    defeatBody: "You are dragged back to safety and lose some gold.",
    continue: "Continue",
    miss: "Miss",
    gold: "Gold",
    food: "Food",
    ore: "Ore",
    healthPotions: "Health Potions",
    manaPotions: "Mana Potions",
    resources: "Resources",
    inn: "Inn",
    market: "Market",
    blacksmith: "Blacksmith",
    tavern: "Tavern",
    mine: "Mine",
    backpack: "Backpack",
    equipped: "Equipped",
    empty: "Empty",
    characterAppearance: "Character Appearance",
    equipBest: "Equip Best",
    sellWorse: "Sell Worse",
    sellAllUnequipped: "Sell All Unequipped",
    sell: "Sell",
    attackShort: "Atk",
    defenseShort: "Def",
    quality_poor: "Poor",
    quality_common: "Common",
    quality_fine: "Fine",
    quality_rare: "Rare",
    quality_effect: "Effect",
    buy: "Buy",
    hire: "Hire",
    reroll: "Reroll",
    upgrade: "Upgrade",
    basicSupplies: "Basic Supplies",
    basicGear: "Basic Gear",
    buyHealthPotion: "Buy Health Potion",
    buyManaPotion: "Buy Mana Potion",
    buyFood: "Buy Food",
    marketRefresh: "Stock refreshes each day. Rerolling costs gold.",
    tavernRefresh: "Recruits refresh each day. Rerolling costs gold.",
    upkeep: "Upkeep",
    activeCompanions: "Active companions",
    monthlyWages: "Monthly wages",
    dailyFoodNeed: "Daily food need",
    noCompanions: "No companions hired yet.",
    noCompanionsHelp: "Recruit companions at taverns or find named allies during story events.",
    companionSystemHelp: "Set who fights, choose tactics, train companions, and build bond through active battles.",
    companionBook: "Book",
    role: "Role",
    tactic: "Tactic",
    bond: "Bond",
    bondGrew: "Bond grew",
    training: "Training",
    train: "Train",
    trained: "Trained",
    bench: "Bench",
    benched: "Benched",
    activate: "Activate",
    speed: "Speed",
    loyalty: "Loyalty",
    morale: "Morale",
    partyFull: "Party Full",
    partyFullBody: "Bench another companion before activating this one.",
    noGearEquipped: "No item equipped.",
    upgradeCost: "Next upgrade",
    fullyUpgraded: "Fully upgraded.",
    upgraded: "Upgraded",
    mineForOre: "Mine for Ore",
    mineResult: "Mine Results",
    mineBody: "Spend 5 days gathering ore for blacksmith upgrades.",
    mineGathered: "You gathered ore over 5 days.",
    needGold: "Need more gold.",
    needOre: "Need more ore.",
    needFood: "Need more food.",
    bought: "Bought",
    hired: "Hired",
    stockRefreshesDaily: "Refreshes daily",
    day: "Day",
    level: "Lv",
    classStats: {
      strength: "Physical damage and heavy weapon power.",
      wisdom: "Magic, healing, and mana-driven skills.",
      endurance: "Maximum HP and survival.",
      speed: "Turn order and dodging.",
      luck: "Criticals, drops, and odd chances."
    },
    statNames: {strength:"Strength", wisdom:"Wisdom", endurance:"Endurance", speed:"Speed", luck:"Luck"},
    initialStory: [
      "Ser Kael fell beneath the dragon, but his barrier saved you.",
      "You woke below Ashen Keep with smoke in your lungs, gate debt on your name, and a class path burning in your blood.",
      "Cinderhook Slum is your first refuge. The Lower Ward gate is visible above the roofs.",
      "Every day costs food. Every choice changes coin, safety, reputation, and gang pressure."
    ],
    story: "Story",
    current: "Current",
    travel: "Travel",
    regions: {
      ashen_fields:{name:"Ashen Fields",desc:"Burned roads, low ruins, and the first safe hunts."},
      green_march:{name:"Green March",desc:"Bandits, beasts, and old watchtowers swallowed by vines."},
      frostmere:{name:"Frostmere",desc:"Frozen lakes and soldiers who never came home."},
      storm_coast:{name:"Storm Coast",desc:"Lightning over black cliffs and raiders under torn sails."},
      hollow_kingdom:{name:"Hollow Kingdom",desc:"Dead banners still fly above cursed roads and ancient cities."}
    },
    dragonMoments: [
      ["Radiant Guard", "Ser Kael plants his sword into the stone. A shield of pale gold surrounds you.", 0, 0],
      ["Crossing Blades", "Kael rushes forward. Two sword arcs carve across the dragon's chest.", 0, 620],
      ["Dragonfire", "The dragon exhales black flame. Kael holds the line, but his armor begins to glow red.", 720, 0],
      ["Last Blade", "Kael leaps into the smoke and drives his sword under the dragon's jaw.", 0, 870],
      ["The Crush", "The dragon catches Kael in its claws. The old knight looks back once, making sure the barrier still holds.", 2600, 0]
    ],
    dragonStart: ["A diseased dragon crashes through the ruined gate.", "Ser Kael steps between you and death."],
    kaelDamage: "Ser Kael damages the Diseased Dragon for",
    dragonDamage: "The Diseased Dragon hits Ser Kael for",
    wakeStory: [
      "You wake in a shelter under Ashen Keep. The healer says Kael is gone.",
      "The dragon did not kill you, but it marked your life. Cinderhook Slum becomes your first refuge, your first debt, and the beginning of your climb."
    ]
  },
  es: {
    gameTitle: "Beneath the Throne",
    startSubtitle: "Entra en un reino en ruinas entre ceniza, niebla y el camino hacia Ashen Keep.",
    startNote: "Nueva Partida empieza con un tutorial cinematografico, el evento del dragon/Ser Kael y despues la seleccion de clase.",
    heroName: "Nombre del héroe",
    newGame: "Nueva Partida",
    loadGame: "Cargar Partida",
    language: "Idioma",
    english: "English",
    spanish: "Español",
    selected: "Seleccionado",
    tutorialBattle: "Batalla Tutorial",
    tutorialSub: "Aprende combate antes de la caída de Ashen Keep.",
    goal: "Objetivo",
    skeletonGoal: "Derrota al esqueleto. Usa Atacar, Poción y Defender para ver qué hace cada acción.",
    unchosenSurvivor: "Sobreviviente sin senda",
    roadSkeleton: "Esqueleto del camino",
    tutorialEnemy: "Enemigo tutorial",
    attack: "Atacar",
    skills: "Habilidades",
    skill: "Habilidad",
    healthPotion: "Pocion de salud",
    manaPotion: "Pocion de mana",
    potion: "Poción",
    defend: "Defender",
    help: "Ayuda",
    skip: "Saltar",
    mana: "Maná",
    hp: "PV",
    round: "Ronda",
    yourTurn: "turno",
    noClass: "Todavía no elegiste una clase. Derrota primero al esqueleto. Tus verdaderas habilidades despiertan después del evento del dragón.",
    notEnoughMana: "No tienes suficiente maná.",
    noPotions: "No quedan pociones.",
    noManaPotions: "No quedan pociones de mana.",
    manaFull: "El mana ya esta lleno.",
    skeletonHit: "Esqueleto del Camino araña a",
    heroHits: "ataca por",
    heroHealthPotion: "bebe una pocion de salud y restaura",
    heroManaPotion: "bebe una pocion de mana y restaura",
    heroPotion: "bebe una poción y restaura 35 PV.",
    heroDefend: "defiende. El siguiente golpe se reduce.",
    combatBasics: "Conceptos de Combate",
    combatBasicsBody: "El combate es por turnos. Atacar causa daño estable, Poción restaura PV, Defender reduce el siguiente golpe y las habilidades de clase se desbloquean tras sobrevivir al evento del dragón.",
    firstVictory: "Primera Victoria",
    firstVictoryBody: "El esqueleto se derrumba. El camino queda en silencio, pero Ashen Keep ya arde más adelante.",
    continueKeep: "Continuar bajo el Bastion",
    dragonTitle: "El Dragón en Ashen Keep",
    dragonSub: "Esta no es una pelea normal. Este es el evento que crea a tu personaje.",
    survivor: "Sobreviviente",
    diseasedDragon: "Dragón Enfermo",
    radiantKnight: "Caballero radiante",
    protectedSurvivor: "Sobreviviente protegido",
    dragonPortraitText: "Dragon marcado por la peste",
    barrier: "Barrera",
    nextMoment: "Siguiente Momento",
    wakeKeep: "Despertar bajo el Bastion",
    ashenKeep: "Ashen Keep",
    chooseClass: "Elegir Clase",
    choosePath: "Elige Tu Camino",
    pathSub: "El ataque del dragón te deja apenas con vida. Un campeón caído te protege lo suficiente para despertar tu primera clase.",
    pathNote: "Cada clase cambia tus estadísticas iniciales, habilidades y el ritmo de tus primeras peleas.",
    choose: "Elegir",
    classNames: {
      warrior: "Guerrero",
      rogue: "Picaro",
      mage: "Mago",
      ranger: "Explorador",
      cleric: "Clerigo"
    },
    classFlavor: {
      warrior: "Una senda de primera linea que convierte el dolor en presion y sostiene el camino cuando otros caen.",
      rogue: "Una hoja en el humo, hecha para velocidad, aperturas sucias y castigos antes de que el enemigo responda.",
      mage: "Un erudito marcado por fuego y fuerza arcana, fragil hasta que el campo se vuelve circulo ritual.",
      ranger: "Un cazador de caminos que lee rastros, controla distancia y sobrevive donde los mapas dejan de mentir.",
      cleric: "Un guardian de juramentos y amparos que lleva luz sanadora por ruinas que quieren apagarla."
    },
    mainTutorialTitle: "Tutorial: Cinderhook",
    mainTutorialBody: "Empiezas en el barrio bajo de Cinderhook. Usa Ganar moneda, Limpiar callejon, Refugio y aliado, Presion de bandas y la Puerta del Barrio Bajo para sobrevivir el prologo. Las cartas de PNJ abren suministros, forja, descanso, rumores, Mira y la banda.",
    close: "Cerrar",
    save: "Guardar",
    load: "Cargar",
    emptySlot: "Ranura Vacía",
    damagedSave: "Partida Dañada",
    noSave: "No hay partida guardada en esa ranura.",
    home: "Hogar",
    town: "Ciudad",
    gear: "Equipo",
    party: "Grupo",
    companion: "Companero",
    stats: "Estadisticas",
    classes: "Clases",
    weapons: "Armas",
    mastery: "Maestria",
    abilityBook: "Libro de habilidades",
    knownAbilities: "Habilidades conocidas",
    activeAbilitySlots: "Ranuras de habilidad activas",
    activeInCombat: "Solo las habilidades activas aparecen en combate.",
    slot: "Ranura",
    equip: "Equipar",
    unequip: "Quitar",
    active: "Activa",
    emptyAbilitySlot: "Ranura de habilidad vacia.",
    noActiveAbilities: "No hay habilidades activas equipadas.",
    abilityNotActive: "Esa habilidad no esta equipada.",
    abilityCost: "Costo de mana",
    abilityMilestone: "Hito de habilidad",
    chooseNewAbility: "Elige una nueva habilidad para tu libro.",
    learnAbility: "Aprender",
    learnedAbility: "Habilidad aprendida",
    currentClass: "Clase actual",
    activeClass: "Activa",
    baseClass: "Clase base",
    classPath: "Camino de clase",
    classPaths: "Caminos de clase",
    baseClassPathBody: "Tu entrenamiento original sigue disponible.",
    unlockClass: "Desbloquear clase",
    switchClass: "Cambiar clase",
    classUnlocked: "Clase desbloqueada",
    classChanged: "Clase cambiada",
    unlocked: "Desbloqueada",
    locked: "Bloqueada",
    available: "Disponible",
    requiresLevel: "Requiere nivel",
    weaponMastery: "Maestria de arma",
    spellMastery: "Maestria de hechizos",
    currentWeapon: "Arma actual",
    weaponType: "Tipo de arma",
    critBonus: "Critico",
    damageBonus: "Dano",
    spellDamage: "Hechizo",
    healingBonus: "Sanacion",
    classMastery: "Maestria de clase",
    cmAllocation: "Asignacion de XP a maestria",
    cmAllocationHelp: "Elige cuanta XP de batalla se convierte en XP de maestria en lugar de XP normal.",
    cmXp: "XP de maestria",
    cmPoints: "Puntos de maestria",
    cmSpent: "Maestria gastada",
    cmNextPoint: "Siguiente punto",
    cmAvailable: "Disponible",
    cmPurchased: "Comprada",
    cmLocked: "Bloqueada",
    cmCost: "Costo",
    cmRequires: "Requiere",
    cmRequiresLevel: "Requiere nivel",
    cmRequiresSpent: "Requiere maestria gastada",
    cmRequiresNode: "Requiere maestria",
    cmNoNodes: "No hay nodos de maestria para esta clase.",
    cmBranches: {
      Vanguard: "Vanguardia",
      Breaker: "Rompedor",
      Bulwark: "Baluarte",
      Knives: "Cuchillas",
      Shadows: "Sombras",
      Arcane: "Arcano",
      Elemental: "Elemental",
      Marksman: "Tirador",
      Wilds: "Tierras salvajes",
      Restoration: "Restauracion",
      Warding: "Amparo",
      Judgment: "Juicio",
      Path: "Camino",
      Signature: "Firma",
      Capstone: "Cumbre"
    },
    cmNotEnoughPoints: "Necesitas mas puntos de maestria.",
    cmMasteryBought: "Maestria aprendida",
    normalXp: "XP normal",
    classMasteryXp: "XP de maestria",
    xpSplit: "Division de XP",
    boughtStatus: "Comprada",
    progression: "Progresión",
    map: "Mapa",
    kingdoms: "Reinos",
    currentLocation: "Lugar actual",
    openMap: "Abrir mapa",
    overworldMap: "Mapa del mundo",
    overworldHelp: "Elige un lugar conectado en el mapa. Tu marcador sigue el camino; el viaje puede ser interrumpido.",
    mapActivity: "Actividad del mapa",
    mapEntityCaravan: "Caravana mercante",
    mapEntityPatrol: "Patrulla del camino",
    mapEntityMonster: "Monstruo errante",
    mapEntityAdventurer: "Aventurero errante",
    mapEventCampfire: "Fogata",
    mapEventCrashedCaravan: "Caravana destruida",
    mapEventStrangeGlow: "Brillo magico extrano",
    mapEventBurningVillage: "Marca de aldea en llamas",
    mapEventMonsterNest: "Nido de monstruos",
    mapEventTravelingMerchant: "Mercader viajero",
    playerMarker: "Marcador del jugador",
    travelingTo: "Viajando a",
    travelInProgress: "Viaje en curso",
    travelAmbush: "Emboscada!",
    travelAmbushBody: "Algo se mueve entre la ceniza...",
    travelStrangeEvent: "Senal extrana del camino",
    travelStrangeEventBody: "El camino se curva entre humo viejo y susurros antes de calmarse.",
    travelMerchantEvent: "Mercader del camino",
    travelMerchantEventBody: "Un viajero cauteloso comparte provisiones antes de perderse en la ceniza.",
    travelDiscoveryEvent: "Descubrimiento del camino",
    travelDiscoveryEventBody: "Encuentras un alijo medio enterrado junto al camino.",
    travelRoadStop: "Parada del camino",
    currentRoadStop: "Parada actual del camino",
    destination: "Destino",
    journeyProgress: "Progreso del viaje",
    roadCondition: "Estado del camino",
    roadConditionUncertain: "Incierto",
    roadStopDefaultDesc: "El camino se calma por un momento, aunque la ceniza nunca se asienta del todo.",
    continueJourney: "Continuar viaje",
    inspectArea: "Inspeccionar area",
    turnBack: "Regresar",
    turnBackDisabled: "Regresar solo esta disponible en paradas tras dejar el origen.",
    journeyNotReady: "No estas detenido en el camino.",
    roadStopAlreadyInspected: "Ya registraste esta parada.",
    roadStopInspectFound: "Descubres un pequeno alijo junto al camino.",
    roadStopInspectQuiet: "Encuentras huellas y ceniza fria, pero nada util.",
    roadStopAfterBattle: "El camino vuelve a ser tuyo. La ceniza cae sobre los derrotados.",
    forceTravelEncounterReady: "El siguiente tramo de viaje forzara un encuentro.",
    travelingBetweenRoadStops: "Viajando entre paradas del camino.",
    noServicesOnRoad: "No hay servicios disponibles en este camino.",
    establishCamp: "Establecer campamento",
    futureSystem: "Sistema futuro",
    cannotBuildHere: "No se puede construir aqui",
    controlledTerritory: "Territorio controlado",
    dangerousRoad: "Camino peligroso",
    tooCloseToTown: "Demasiado cerca de los muros del pueblo",
    nearbyThreats: "Amenazas cercanas",
    strategicValue: "Valor estrategico",
    cancelTravel: "Cancelar viaje",
    alreadyTraveling: "Ya estas viajando.",
    travelCanceled: "Viaje cancelado.",
    enterLocation: "Lugar",
    routes: "Rutas",
    localActions: "Acciones locales",
    localActionsHelp: "Rastrea para hallazgos pequenos o caza cuando quieras una batalla cercana.",
    services: "Servicios",
    locationServices: "Servicios del lugar",
    noServicesHere: "No hay servicios disponibles aqui.",
    serviceUnavailable: "Ese servicio no esta disponible en este lugar.",
    travelTo: "Viajar a",
    returnTo: "Volver a",
    backToLocation: "Volver al lugar",
    huntNearby: "Cazar cerca",
    scoutNearby: "Rastrear cerca",
    hardAreas: "Zonas dificiles",
    hardAreasHelp: "Peleas de alto riesgo con grupos enemigos mas fuertes y mejores recompensas. Sirven para probar builds, companeros, pociones y maestria de clase.",
    enterHardArea: "Entrar a zona dificil",
    hardAreaLocked: "Esa zona dificil no esta disponible desde aqui.",
    hardAreaStarted: "Zona dificil iniciada",
    hardAreaCleared: "Zona dificil superada",
    recommendedLevel: "Nivel recomendado",
    enemyCount: "Enemigos",
    highRisk: "Alto riesgo",
    cleared: "Superada",
    attempts: "Intentos",
    danger: "Peligro",
    unknownLocation: "Lugar desconocido.",
    routeLocked: "No hay ruta desde aqui.",
    connectedRoutes: "Rutas conectadas",
    travelFromMapHelp: "Toca un nodo conectado en el mapa o usa una ruta de abajo para viajar.",
    noPreviousLocation: "No hay lugar anterior.",
    travelEncounter: "Encuentro en el camino",
    travelResource: "Hallazgo de viaje",
    arrivedAt: "Llegaste a",
    scoutEncounter: "Encuentro de exploracion",
    scoutFind: "Hallazgo de exploracion",
    worldMap: "Rutas del mundo",
    worldMapBody: "Usa el mapa para rutas del mundo, lugares conectados y viaje guiado. Los edificios y acciones locales viven en la pantalla del lugar actual.",
    kingdomWorldBody: "La presion de los reinos aun se registra por region. Mas adelante las guerras y asentamientos se uniran a nodos concretos.",
    kingdomLocation: "Base regional",
    combat: "Combate",
    enemies: "Enemigos",
    battleLog: "Registro de batalla",
    turnOrder: "Orden de turnos",
    explore: "Explorar",
    hunt: "Cacería Peligrosa",
    boss: "Jefe Regional",
    rest: "Descansar",
    camp: "Acampar",
    run: "Huir",
    auto: "Bot de Pelea",
    victory: "Recompensas de Victoria",
    defeat: "Derrota",
    defeatBody: "Te arrastran a un lugar seguro y pierdes algo de oro.",
    continue: "Continuar",
    miss: "Falla",
    gold: "Oro",
    food: "Comida",
    ore: "Mineral",
    healthPotions: "Pociones de salud",
    manaPotions: "Pociones de mana",
    resources: "Recursos",
    inn: "Posada",
    market: "Mercado",
    blacksmith: "Herreria",
    tavern: "Taberna",
    mine: "Mina",
    backpack: "Mochila",
    equipped: "Equipado",
    empty: "Vacio",
    characterAppearance: "Apariencia del personaje",
    equipBest: "Equipar mejor",
    sellWorse: "Vender peores",
    sellAllUnequipped: "Vender no equipado",
    sell: "Vender",
    attackShort: "Atq",
    defenseShort: "Def",
    quality_poor: "Pobre",
    quality_common: "Comun",
    quality_fine: "Fino",
    quality_rare: "Raro",
    quality_effect: "Efecto",
    buy: "Comprar",
    hire: "Contratar",
    reroll: "Renovar",
    upgrade: "Mejorar",
    basicSupplies: "Suministros basicos",
    basicGear: "Equipo basico",
    buyHealthPotion: "Comprar pocion de salud",
    buyManaPotion: "Comprar pocion de mana",
    buyFood: "Comprar comida",
    marketRefresh: "El inventario se renueva cada dia. Renovar cuesta oro.",
    tavernRefresh: "Los reclutas se renuevan cada dia. Renovar cuesta oro.",
    upkeep: "Mantenimiento",
    activeCompanions: "Companeros activos",
    monthlyWages: "Salarios mensuales",
    dailyFoodNeed: "Comida diaria",
    noCompanions: "Aun no has contratado companeros.",
    noCompanionsHelp: "Recluta companeros en tabernas o encuentra aliados con nombre durante eventos de historia.",
    companionSystemHelp: "Elige quien pelea, cambia tacticas, entrena companeros y sube vinculo en batallas activas.",
    companionBook: "Libro",
    role: "Rol",
    tactic: "Tactica",
    bond: "Vinculo",
    bondGrew: "El vinculo crecio",
    training: "Entrenamiento",
    train: "Entrenar",
    trained: "Entrenado",
    bench: "Reservar",
    benched: "Reserva",
    activate: "Activar",
    speed: "Velocidad",
    loyalty: "Lealtad",
    morale: "Moral",
    partyFull: "Grupo lleno",
    partyFullBody: "Reserva otro companero antes de activar este.",
    noGearEquipped: "No hay objeto equipado.",
    upgradeCost: "Siguiente mejora",
    fullyUpgraded: "Mejora maxima.",
    upgraded: "Mejorado",
    mineForOre: "Extraer mineral",
    mineResult: "Resultados de la mina",
    mineBody: "Pasa 5 dias reuniendo mineral para mejoras de herreria.",
    mineGathered: "Reuniste mineral durante 5 dias.",
    needGold: "Necesitas mas oro.",
    needOre: "Necesitas mas mineral.",
    needFood: "Necesitas mas comida.",
    bought: "Comprado",
    hired: "Contratado",
    stockRefreshesDaily: "Se renueva cada dia",
    day: "Día",
    level: "Nv",
    classStats: {
      strength: "Daño físico y poder con armas pesadas.",
      wisdom: "Magia, sanación y habilidades de maná.",
      endurance: "PV máximos y supervivencia.",
      speed: "Orden de turnos y evasión.",
      luck: "Críticos, botín y oportunidades extrañas."
    },
    statNames: {strength:"Fuerza", wisdom:"Sabiduría", endurance:"Resistencia", speed:"Velocidad", luck:"Suerte"},
    initialStory: [
      "Ser Kael cayó bajo el dragón, pero su barrera te salvó.",
      "Despertaste bajo Ashen Keep con humo en los pulmones, deuda de puerta en tu nombre y un camino de clase ardiendo en tu sangre.",
      "Cinderhook es tu primer refugio. La puerta del Barrio Bajo se ve sobre los techos.",
      "Cada día cuesta comida. Cada decisión cambia moneda, seguridad, reputación y presión de bandas."
    ],
    story: "Historia",
    current: "Actual",
    travel: "Viajar",
    regions: {
      ashen_fields:{name:"Campos de Ceniza",desc:"Caminos quemados, ruinas bajas y las primeras cacerías seguras."},
      green_march:{name:"Marca Verde",desc:"Bandidos, bestias y viejas torres cubiertas por enredaderas."},
      frostmere:{name:"Frostmere",desc:"Lagos congelados y soldados que nunca volvieron a casa."},
      storm_coast:{name:"Costa de Tormentas",desc:"Relámpagos sobre acantilados negros y saqueadores bajo velas rotas."},
      hollow_kingdom:{name:"Reino Hueco",desc:"Banderas muertas aún ondean sobre caminos malditos y ciudades antiguas."}
    },
    dragonMoments: [
      ["Guardia Radiante", "Ser Kael clava su espada en la piedra. Un escudo de oro pálido te rodea.", 0, 0],
      ["Cruce de Espadas", "Kael avanza. Dos arcos de espada cortan el pecho del dragón.", 0, 620],
      ["Fuego del Dragón", "El dragón exhala fuego negro. Kael mantiene la línea, pero su armadura empieza a brillar roja.", 720, 0],
      ["Última Espada", "Kael salta entre el humo y hunde su espada bajo la mandíbula del dragón.", 0, 870],
      ["El Aplastamiento", "El dragón atrapa a Kael con sus garras. El viejo caballero mira una vez más para asegurar que la barrera aguante.", 2600, 0]
    ],
    dragonStart: ["Un dragón enfermo atraviesa la puerta destruida.", "Ser Kael se interpone entre tú y la muerte."],
    kaelDamage: "Ser Kael daña al Dragón Enfermo por",
    dragonDamage: "El Dragón Enfermo golpea a Ser Kael por",
    wakeStory: [
      "Despiertas en un refugio bajo Ashen Keep. La sanadora dice que Kael ha muerto.",
      "El dragon no te mato, pero marco tu vida. Cinderhook sera tu primer refugio, tu primera deuda y el inicio de tu ascenso."
    ]
  }
};

let currentLanguage = loadLanguage();

function loadLanguage(){
  try{return localStorage.getItem(LANGUAGE_KEY)==="es"?"es":"en";}catch(e){return"en";}
}

export function setLanguage(lang){
  currentLanguage = lang==="es" ? "es" : "en";
  try{localStorage.setItem(LANGUAGE_KEY,currentLanguage);}catch(e){}
  document.documentElement.lang = currentLanguage;
}

export function getLanguage(){
  return currentLanguage;
}

export function dictionary(){
  return TEXT[currentLanguage] || TEXT.en;
}

export function tx(key){
  return dictionary()[key] ?? TEXT.en[key] ?? key;
}

export function title(text){
  return String(text).replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
}

export function statExplanation(stat){
  const stats = dictionary().classStats || TEXT.en.classStats;
  return stats[stat] || stat;
}

export function statName(stat){
  const names = dictionary().statNames || TEXT.en.statNames;
  return names[stat] || title(stat);
}

export function regionText(region, field){
  const regions = dictionary().regions || TEXT.en.regions;
  return regions[region.id]?.[field] || region[field] || region.id;
}
