const LANGUAGE_KEY = "fallenEmpireLanguage";

export const TEXT = {
  en: {
    gameTitle: "Beneath the Throne",
    startSubtitle: "Enter a ruined kingdom through ash, fog, and the road to Ashen Keep.",
    startNote: "New Game begins with a cinematic tutorial, the Ser Kael dragon event, then class selection.",
    heroName: "Hero name",
    newGame: "New Game",
    loadGame: "Load Game",
    language: "Language",
    english: "English",
    spanish: "Español",
    selected: "Selected",
    tutorialBattle: "Tutorial Battle",
    tutorialSub: "Learn combat before the fall of Ashen Keep.",
    goal: "Goal",
    skeletonGoal: "Defeat the skeleton. Use Attack, Potion, and Defend to see what each action does.",
    unchosenSurvivor: "Unchosen survivor",
    roadSkeleton: "Road Skeleton",
    tutorialEnemy: "Tutorial enemy",
    attack: "Attack",
    skills: "Skills",
    skill: "Skill",
    potion: "Potion",
    healthPotion: "Health Potion",
    manaPotion: "Mana Potion",
    defend: "Defend",
    help: "Help",
    skip: "Skip",
    mana: "Mana",
    hp: "HP",
    round: "Round",
    yourTurn: "turn",
    combatTurnPlayer: "Your turn.",
    combatTurnResolving: "Resolving turns...",
    combatTarget: "Target",
    townCenter: "Town Center",
    slumPrologue: "Slum Prologue",
    slumPrologueTitle: "Cinderhook Slum",
    slumPrologueDesc: "Earn coin, build a name, survive gang pressure, and reach the Lower Ward gate.",
    slumPrologueComplete: "The gate has opened. The full climb toward castle society is ready to become the paid game arc.",
    slumContracts: "Contracts",
    slumTownWork: "Town & Work",
    slumShelterAlly: "Shelter & Ally",
    slumGateReady: "Lower Ward Gate Reached",
    slumGateTest: "Approach the Lower Ward Gate",
    slumGateOpened: "opened",
    slumGateLocked: "locked",
    slumGateReadyLabel: "ready",
    slumRecentRumors: "Recent Rumors",
    slumTownContacts: "Town Contacts & Services",
    slumChapterBoard: "Chapter 1 Board",
    slumContractBoardDesc: "One focused job at a time. Contracts move coin, reputation, safety, Mira, and the Lower Ward gate together.",
    slumContractBoardComplete: "Cinderhook knows your name. The Lower Ward road is open beyond the gate.",
    slumContractBossReady: "Boss ready",
    slumContractNoNew: "No new contract",
    slumContractNoNewGate: "Finish the gate requirements or check the Lower Ward gate.",
    slumContractNoNewMira: "Find and recruit Mira to unlock the Chapter 1 boss route.",
    contractAccept: "Accept",
    contractHold: "Hold",
    contractDetails: "Details",
    contractDone: "done",
    contract_ration_marks_name: "Recover Stolen Food",
    contract_ration_marks_desc: "Trace missing food sacks through the drain alleys before the Dock Rats sell them back.",
    contract_ration_marks_action: "Search Drains",
    contract_ration_marks_tag: "Market",
    contract_ration_marks_log: "You recover marked ration sacks and return them before the market opens.",
    contract_forge_scrap_name: "Bring Borin Scrap",
    contract_forge_scrap_desc: "Work the ash heaps for usable scrap so Borin can patch weapons without asking questions.",
    contract_forge_scrap_action: "Work Scrap Run",
    contract_forge_scrap_tag: "Blacksmith",
    contract_forge_scrap_log: "You haul usable scrap to Borin. He marks your name on the honest side of the ledger.",
    contract_knife_corner_name: "Clear Knife-Corner",
    contract_knife_corner_desc: "A corner crew waits near the smoke ditch. Clear it and the shelter route gets safer.",
    contract_knife_corner_action: "Start Fight",
    contract_knife_corner_tag: "Alley Fight",
    contract_knife_corner_log: "Knife-Corner empties out. Doors open a little wider when you pass.",
    contract_dock_rat_ledger_name: "Break the Dock Rat Ledger",
    contract_dock_rat_ledger_desc: "Vale knows where the Dock Rats keep the debt list. Burn it before they move collections.",
    contract_dock_rat_ledger_action: "Raid Ledger",
    contract_dock_rat_ledger_tag: "Gang",
    contract_dock_rat_ledger_log: "The Dock Rat debt ledger burns in a tavern stove. Several families stop whispering your name like a warning.",
    contract_gate_lieutenant_name: "Defeat the Gate Lieutenant",
    contract_gate_lieutenant_desc: "The gang lieutenant who sells gate access has stopped hiding behind collectors. Beat him and Chapter 1 has a real ending.",
    contract_gate_lieutenant_action: "Challenge Lieutenant",
    contract_gate_lieutenant_tag: "Chapter Boss",
    contract_gate_lieutenant_log: "The gate lieutenant drops to one knee. Cinderhook sees the Lower Ward path crack open.",
    noClass: "You have not chosen a class. Defeat the skeleton first. Your real abilities awaken after the dragon event.",
    notEnoughMana: "Not enough mana.",
    noPotions: "No potions left.",
    noManaPotions: "No mana potions left.",
    manaFull: "Mana is already full.",
    skeletonHit: "Road Skeleton claws",
    heroHits: "attacks for",
    heroPotion: "drinks a potion and restores 35 HP.",
    heroHealthPotion: "drinks a health potion and restores",
    heroManaPotion: "drinks a mana potion and restores",
    heroDefend: "defends. The next hit is reduced.",
    combatBasics: "Combat Basics",
    combatBasicsBody: "Combat is turns. Attack hits. Defend cuts the next hit. Potion heals. Class skills unlock after Ser Kael. The highlighted button is the lesson.",
    lessonAttack: "Lesson 1 of 3 — Attack",
    lessonAttackBody: "Tap Attack. Steel first. The bones will answer.",
    lessonDefend: "Lesson 2 of 3 — Defend",
    lessonDefendBody: "Tap Defend. Guarding cuts the next blow almost in half.",
    lessonPotion: "Lesson 3 of 3 — Potion",
    lessonPotionBody: "Tap Potion. Healing is a turn — the skeleton still swings after you drink.",
    lessonFinish: "Finish it",
    lessonFinishBody: "Attack until the skeleton falls. Skip is always there if you already know this.",
    lessonWait: "The skeleton answers...",
    lessonLocked: "Only the glowing button works. Skip if you already know this fight.",
    firstVictory: "First Victory",
    firstVictoryBody: "The skeleton collapses. The road falls silent, but Ashen Keep is already burning ahead.",
    continueKeep: "Continue Below the Keep",
    dragonTitle: "The Dragon at Ashen Keep",
    dragonSub: "This is not a normal fight. This is the event that creates your character.",
    survivor: "Survivor",
    diseasedDragon: "Diseased Dragon",
    radiantKnight: "Radiant knight",
    protectedSurvivor: "Protected survivor",
    dragonPortraitText: "Plague-marked dragon",
    barrier: "Barrier",
    nextMoment: "Next Moment",
    wakeKeep: "Wake Below the Keep",
    ashenKeep: "Ashen Keep",
    chooseClass: "Choose Class",
    choosePath: "Choose Your Path",
    pathSub: "The dragon attack leaves you barely alive. A fallen champion shields you long enough to awaken your first class.",
    pathNote: "Each class changes starting stats, starter abilities, and the way your early fights feel.",
    choose: "Choose",
    classNames: {
      warrior: "Warrior",
      rogue: "Rogue",
      mage: "Mage",
      ranger: "Ranger",
      cleric: "Cleric"
    },
    classFlavor: {
      warrior: "A sworn front-line survivor who turns pain into pressure and holds the road when others break.",
      rogue: "A knife in the smoke, built for speed, dirty openings, and punishing enemies before they can answer.",
      mage: "A marked scholar of fire and arcane force, fragile until the battlefield becomes your ritual circle.",
      ranger: "A roadwise hunter who reads tracks, controls distance, and survives where maps stop being honest.",
      cleric: "A keeper of oaths and wards, carrying healing light through ruins that want every flame extinguished."
    },
    mainTutorialTitle: "How Cinderhook works",
    mainTutorialLead: "This slum is the first climb. Do these in order — the buttons match the names below.",
    mainTutorialStep1: "Contracts — accept Recover Stolen Food and fight in the alleys.",
    mainTutorialStep2: "Town & Work — supplies, forge, rest, and tavern rumors.",
    mainTutorialStep3: "Shelter & Ally — Mira waits here. Bring her when you can.",
    mainTutorialStep4: "Approach the Lower Ward Gate when gold, reputation, and safety are high enough.",
    mainTutorialStep5: "Map (bottom dock) leaves Cinderhook after the gate opens.",
    mainTutorialStep6: "The scales icon is the Court Ledger. It sells looks, not power.",
    close: "Close",
    mute: "Mute",
    unmute: "Unmute",
    music: "Music",
    soundFx: "Fight sounds",
    audioOn: "On",
    audioOff: "Off",
    save: "Save",
    load: "Load",
    emptySlot: "Empty Slot",
    damagedSave: "Damaged Save",
    noSave: "No save in that slot.",
    home: "Home",
    town: "Town",
    gear: "Gear",
    party: "Party",
    companion: "Companion",
    progression: "Progression",
    stats: "Stats",
    classes: "Classes",
    weapons: "Weapons",
    mastery: "Mastery",
    abilityBook: "Ability Book",
    knownAbilities: "Known Abilities",
    activeAbilitySlots: "Active Ability Slots",
    activeInCombat: "Only active abilities appear in combat.",
    slot: "Slot",
    equip: "Equip",
    unequip: "Unequip",
    active: "Active",
    emptyAbilitySlot: "Empty ability slot.",
    noActiveAbilities: "No active abilities equipped.",
    abilityNotActive: "That ability is not equipped.",
    abilityCost: "Mana cost",
    abilityMilestone: "Ability Milestone",
    chooseNewAbility: "Choose one new ability for your Ability Book.",
    learnAbility: "Learn",
    learnedAbility: "Learned ability",
    currentClass: "Current Class",
    activeClass: "Active",
    baseClass: "Base Class",
    classPath: "Class Path",
    classPaths: "Class Paths",
    baseClassPathBody: "Your original training remains available.",
    unlockClass: "Unlock Class",
    switchClass: "Switch Class",
    classUnlocked: "Class unlocked",
    classChanged: "Class changed",
    unlocked: "Unlocked",
    locked: "Locked",
    available: "Available",
    requiresLevel: "Requires level",
    weaponMastery: "Weapon Mastery",
    spellMastery: "Spell Mastery",
    currentWeapon: "Current Weapon",
    weaponType: "Weapon Type",
    critBonus: "Crit",
    damageBonus: "Damage",
    spellDamage: "Spell",
    healingBonus: "Healing",
    classMastery: "Class Mastery",
    cmAllocation: "Class Mastery XP Allocation",
    cmAllocationHelp: "Choose how much earned battle XP becomes Class Mastery XP instead of normal level XP.",
    cmXp: "CM XP",
    cmPoints: "CM Points",
    cmSpent: "Spent CM",
    cmNextPoint: "Next CM Point",
    cmAvailable: "Available",
    cmPurchased: "Purchased",
    cmLocked: "Locked",
    cmCost: "Cost",
    cmRequires: "Requires",
    cmRequiresLevel: "Requires level",
    cmRequiresSpent: "Requires spent CM",
    cmRequiresNode: "Requires mastery",
    cmNoNodes: "No class mastery nodes for this class.",
    cmBranches: {
      Vanguard: "Vanguard",
      Breaker: "Breaker",
      Bulwark: "Bulwark",
      Knives: "Knives",
      Shadows: "Shadows",
      Arcane: "Arcane",
      Elemental: "Elemental",
      Marksman: "Marksman",
      Wilds: "Wilds",
      Restoration: "Restoration",
      Warding: "Warding",
      Judgment: "Judgment",
      Path: "Path",
      Signature: "Signature",
      Capstone: "Capstone"
    },
    cmNotEnoughPoints: "Need more Class Mastery points.",
    cmMasteryBought: "Mastery learned",
    normalXp: "Normal XP",
    classMasteryXp: "Class Mastery XP",
    xpSplit: "XP Split",
    boughtStatus: "Bought",
    map: "Map",
    kingdoms: "Kingdoms",
    currentLocation: "Current Location",
    openMap: "Open Map",
    overworldMap: "Overworld Map",
    overworldHelp: "Tap a place to inspect it. Gold rings are roads you can take. Then press Travel.",
    mapActivity: "Map Activity",
    mapEntityCaravan: "Merchant caravan",
    mapEntityPatrol: "Road patrol",
    mapEntityMonster: "Roaming monster",
    mapEntityAdventurer: "Wandering adventurer",
    mapEventCampfire: "Campfire",
    mapEventCrashedCaravan: "Crashed caravan",
    mapEventStrangeGlow: "Strange magical glow",
    mapEventBurningVillage: "Burning village marker",
    mapEventMonsterNest: "Monster nest",
    mapEventTravelingMerchant: "Traveling merchant",
    playerMarker: "Player marker",
    travelingTo: "Traveling to",
    travelInProgress: "Travel in progress",
    travelAmbush: "Ambush!",
    travelAmbushBody: "Something moves in the ash...",
    travelStrangeEvent: "Strange Road Sign",
    travelStrangeEventBody: "The road bends through old smoke and whispers before settling again.",
    travelMerchantEvent: "Roadside Trader",
    travelMerchantEventBody: "A wary traveler shares supplies before vanishing into the ash.",
    travelDiscoveryEvent: "Road Discovery",
    travelDiscoveryEventBody: "You find a half-buried cache near the road.",
    travelRoadStop: "Road stop",
    currentRoadStop: "Current Road Stop",
    destination: "Destination",
    journeyProgress: "Journey Progress",
    roadCondition: "Road Condition",
    roadConditionUncertain: "Uncertain",
    roadStopDefaultDesc: "The road quiets for a moment, though the ash never fully settles.",
    continueJourney: "Continue Journey",
    inspectArea: "Inspect Area",
    turnBack: "Turn Back",
    turnBackDisabled: "Turn Back is only available at road stops after leaving the origin.",
    journeyNotReady: "You are not stopped on the road.",
    roadStopAlreadyInspected: "You have already searched this stop.",
    roadStopInspectFound: "You uncover a small cache near the road.",
    roadStopInspectQuiet: "You find tracks and cold ash, but nothing useful.",
    roadStopAfterBattle: "The road is yours again. The ash settles around the fallen.",
    forceTravelEncounterReady: "Next travel segment will force an encounter.",
    travelingBetweenRoadStops: "Traveling between road stops.",
    noServicesOnRoad: "No services available on this road.",
    establishCamp: "Establish Camp",
    campEstablished: "Camp established",
    campAlreadyEstablished: "Camp already established here",
    campActiveSummary: "Your camp is set up at this stop. Rest here safely between journeys.",
    fortifyCamp: "Fortify Camp",
    campFortified: "Camp fortified",
    campFortifiedSummary: "Your fortified camp holds the road. Ambushes are less likely here.",
    campAlreadyFortified: "Camp is already fortified.",
    notEnoughOre: "Not enough ore.",
    notEnoughGold: "Not enough gold.",
    notEnoughFood: "Not enough food.",
    futureSystem: "Future System",
    cannotBuildHere: "Cannot build here",
    controlledTerritory: "Controlled territory",
    dangerousRoad: "Dangerous road",
    tooCloseToTown: "Too close to town walls",
    nearbyThreats: "Nearby threats",
    strategicValue: "Strategic value",
    cancelTravel: "Cancel Travel",
    alreadyTraveling: "Already traveling.",
    travelCanceled: "Travel canceled.",
    enterLocation: "Location",
    routes: "Routes",
    localActions: "Local Actions",
    localActionsHelp: "Scout for small finds or hunt when you want a nearby battle.",
    services: "Services",
    locationServices: "Location Services",
    noServicesHere: "No services are available here.",
    serviceUnavailable: "That service is not available at this location.",
    travelTo: "Travel to",
    returnTo: "Return to",
    backToLocation: "Back to Location",
    huntNearby: "Hunt Nearby",
    scoutNearby: "Scout Nearby",
    hardAreas: "Hard Areas",
    hardAreasHelp: "High-risk fights with stronger enemy groups and better rewards. These are meant to test builds, companions, potions, and class mastery.",
    enterHardArea: "Enter Hard Area",
    hardAreaLocked: "That hard area is not available from here.",
    hardAreaStarted: "Hard area entered",
    hardAreaCleared: "Hard area cleared",
    recommendedLevel: "Recommended Lv",
    enemyCount: "Enemies",
    highRisk: "High Risk",
    cleared: "Cleared",
    attempts: "Attempts",
    danger: "Danger",
    unknownLocation: "Unknown location.",
    routeLocked: "No route from here.",
    connectedRoutes: "Connected Routes",
    travelFromMapHelp: "Tap a place on the map or a road chip below, then travel.",
    youAreHere: "You are here",
    selectedPlace: "Selected",
    tapPlaceToInspect: "Tap a place. Gold pins have a road from here.",
    noRoadFromHere: "No road from your current camp.",
    roadOpen: "A road is open from where you stand.",
    travelInProgress: "On the road",
    distantPlaceHint: "No direct road from here. Travel a connected place first.",
    roadsFromHere: "Roads from here",
    mapZoom: "Map zoom",
    mapZoomIn: "Zoom in",
    mapZoomOut: "Zoom out",
    mapRecenter: "Center on you",
    mapYou: "You",
    mapKey: "Map key",
    legendYou: "You",
    legendOpenRoad: "Open road",
    legendLocked: "Locked",
    statusHere: "Here",
    statusOpen: "Open",
    statusLocked: "Locked",
    statusFar: "Far",
    courtLedger: "Court Ledger",
    courtLedgerTitle: "Ash Court Ledger",
    courtLedgerBody: "Looks, founder identity, extra save beds, and optional crier ads. Combat power stays earned.",
    noPayToWin: "No pay-to-win",
    cosmeticsFirst: "Looks first",
    adsOptional: "Ads optional",
    adsRemoved: "Crier silenced",
    wearingTitle: "You wear",
    offerTagOnce: "Once",
    offerTagConvenience: "Beds",
    offerTagLooks: "Looks",
    offerTagTip: "Tip",
    offerFounderName: "Founder Writ",
    offerFounderDesc: "The fairest first gift: a title, a bronze frame, an ember cloak, extra save beds, and a quiet HUD.",
    offerFounderTitle: "Founder title",
    offerFounderFrame: "Bronze portrait frame",
    offerFounderCloak: "Ember cloak look",
    offerFounderAds: "Silence the crier",
    offerPassName: "Ash Court Pass",
    offerPassDesc: "Two extra save beds and a keep banner. Nothing that wins a fight.",
    offerPassSlots: "Save beds 4 and 5",
    offerPassBanner: "Keep camp banner",
    offerPassAds: "Silence the crier",
    offerCloakName: "Ember Cloak",
    offerCloakDesc: "A coal-red cloak glow on your portrait. Stats stay the same.",
    offerCloakLook: "Ember cloak glow",
    offerFrameName: "Keep Sigil Frame",
    offerFrameDesc: "A gold keep ring around your HUD portrait.",
    offerFrameLook: "Keep portrait ring",
    offerPatronName: "Patron of Ash",
    offerPatronDesc: "A tip with no extras but a title. Helps keep the painted world alive.",
    offerPatronTitle: "Patron of Ash title",
    owned: "Owned",
    buyFor: "Buy",
    whatsInside: "What's inside",
    price: "Price",
    alreadyOwned: "You already hold that writ.",
    offerMissing: "That offer is gone.",
    checkoutMockBody: "Playtest checkout: no real card is charged. Grant the looks on this save so you can feel the shop.",
    checkoutOpensTab: "A checkout tab will open if you pasted a Stripe Payment Link. This save still grants the looks so you can test.",
    openCheckout: "Open checkout",
    payPlaytest: "Pay (playtest)",
    purchaseGranted: "The writ is sealed on this save.",
    ledgerTitle: "Taken in",
    ledgerTaken: "Taken in",
    ledgerEmpty: "No writs sealed yet.",
    ledgerMockNote: "playtest totals until Stripe links are set",
    crierTitle: "Court Crier",
    crierBody: "Once a day, watch a short crier and take a small purse. Never in combat. Never required.",
    watchCrier: "Watch the crier",
    crierDoneToday: "The crier already paid you today",
    crierGone: "You silenced the crier. No more ad purse.",
    crierWatching: "The crier speaks",
    crierWatchBody: "A short playtest stand-in for a rewarded ad. Gold and food come after the bell.",
    crierPaid: "The crier pays",
    realMoneyHow: "How this takes real money",
    realMoneyBody: "Paste Stripe Payment Links into localStorage key btt_checkout_urls as JSON, one URL per offer id. Wrap later for App Store and Play Billing. Ko-fi or Patreon can map to Patron of Ash.",
    realMoneyStripe: "Stripe Payment Links",
    realMoneyStores: "App Store / Play later",
    realMoneyTips: "Ko-fi / Patreon tips",
    noPowerSales: "Classes, companions, and writs of power stay earned in the world.",
    noPreviousLocation: "No previous location.",
    travelEncounter: "Road Encounter",
    travelResource: "Travel Find",
    arrivedAt: "Arrived at",
    scoutEncounter: "Scout Encounter",
    scoutFind: "Scout Find",
    worldMap: "World Routes",
    worldMapBody: "Use the map for overworld routes, connected locations, and guided travel. Local buildings and actions live on the current-location screen.",
    kingdomWorldBody: "Kingdom pressure is still tracked by region. Later passes will bind wars and settlements to specific world nodes.",
    kingdomLocation: "Regional foothold",
    combat: "Combat",
    enemies: "Enemies",
    battleLog: "Battle Log",
    nextUp: "Next",
    turnOrder: "Turn Order",
    explore: "Explore",
    hunt: "Dangerous Hunt",
    boss: "Regional Boss",
    rest: "Rest",
    camp: "Camp",
    run: "Run",
    auto: "Auto",
    victory: "Victory Rewards",
    defeat: "Defeat",
    defeatBody: "You are dragged back to safety and lose some gold.",
    continue: "Continue",
    miss: "Miss",
    gold: "Gold",
    food: "Food",
    ore: "Ore",
    healthPotions: "Health Potions",
    manaPotions: "Mana Potions",
    resources: "Resources",
    inn: "Inn",
    market: "Market",
    blacksmith: "Blacksmith",
    tavern: "Tavern",
    mine: "Mine",
    backpack: "Backpack",
    equipped: "Equipped",
    empty: "Empty",
    characterAppearance: "Character Appearance",
    equipBest: "Equip Best",
    sellWorse: "Sell Worse",
    sellAllUnequipped: "Sell All Unequipped",
    sell: "Sell",
    attackShort: "Atk",
    defenseShort: "Def",
    quality_poor: "Poor",
    quality_common: "Common",
    quality_fine: "Fine",
    quality_rare: "Rare",
    quality_effect: "Effect",
    buy: "Buy",
    hire: "Hire",
    reroll: "Reroll",
    upgrade: "Upgrade",
    basicSupplies: "Basic Supplies",
    basicGear: "Basic Gear",
    buyHealthPotion: "Buy Health Potion",
    buyManaPotion: "Buy Mana Potion",
    buyFood: "Buy Food",
    marketRefresh: "Stock refreshes each day. Rerolling costs gold.",
    tavernRefresh: "Recruits refresh each day. Rerolling costs gold.",
    upkeep: "Upkeep",
    activeCompanions: "Active companions",
    monthlyWages: "Monthly wages",
    dailyFoodNeed: "Daily food need",
    noCompanions: "No companions hired yet.",
    noCompanionsHelp: "Recruit companions at taverns or find named allies during story events.",
    companionSystemHelp: "Set who fights, choose tactics, train companions, and build bond through active battles.",
    companionBook: "Book",
    role: "Role",
    tactic: "Tactic",
    bond: "Bond",
    bondGrew: "Bond grew",
    training: "Training",
    train: "Train",
    trained: "Trained",
    bench: "Bench",
    benched: "Benched",
    activate: "Activate",
    speed: "Speed",
    loyalty: "Loyalty",
    morale: "Morale",
    partyFull: "Party Full",
    partyFullBody: "Bench another companion before activating this one.",
    noGearEquipped: "No item equipped.",
    upgradeCost: "Next upgrade",
    fullyUpgraded: "Fully upgraded.",
    upgraded: "Upgraded",
    mineForOre: "Mine for Ore",
    mineResult: "Mine Results",
    mineBody: "Spend 5 days gathering ore for blacksmith upgrades.",
    mineGathered: "You gathered ore over 5 days.",
    needGold: "Need more gold.",
    needOre: "Need more ore.",
    needFood: "Need more food.",
    bought: "Bought",
    hired: "Hired",
    stockRefreshesDaily: "Refreshes daily",
    day: "Day",
    level: "Lv",
    classStats: {
      strength: "Physical damage and heavy weapon power.",
      wisdom: "Magic, healing, and mana-driven skills.",
      endurance: "Maximum HP and survival.",
      speed: "Turn order and dodging.",
      luck: "Criticals, drops, and odd chances."
    },
    statNames: {strength:"Strength", wisdom:"Wisdom", endurance:"Endurance", speed:"Speed", luck:"Luck"},
    initialStory: [
      "Ser Kael fell beneath the dragon, but his barrier saved you.",
      "You woke below Ashen Keep with smoke in your lungs, gate debt on your name, and a class path burning in your blood.",
      "Cinderhook Slum is your first refuge. The Lower Ward gate is visible above the roofs.",
      "Every day costs food. Every choice changes coin, safety, reputation, and gang pressure."
    ],
    story: "Story",
    current: "Current",
    travel: "Travel",
    regions: {
      ashen_fields:{name:"Ashen Fields",desc:"Burned roads, low ruins, and the first safe hunts."},
      green_march:{name:"Green March",desc:"Bandits, beasts, and old watchtowers swallowed by vines."},
      frostmere:{name:"Frostmere",desc:"Frozen lakes and soldiers who never came home."},
      storm_coast:{name:"Storm Coast",desc:"Lightning over black cliffs and raiders under torn sails."},
      hollow_kingdom:{name:"Hollow Kingdom",desc:"Dead banners still fly above cursed roads and ancient cities."}
    },
    dragonMoments: [
      ["Radiant Guard", "Ser Kael plants his sword into the stone. A shield of pale gold surrounds you.", 0, 0],
      ["Crossing Blades", "Kael rushes forward. Two sword arcs carve across the dragon's chest.", 0, 620],
      ["Dragonfire", "The dragon exhales black flame. Kael holds the line, but his armor begins to glow red.", 720, 0],
      ["Last Blade", "Kael leaps into the smoke and drives his sword under the dragon's jaw.", 0, 870],
      ["The Crush", "The dragon catches Kael in its claws. The old knight looks back once, making sure the barrier still holds.", 2600, 0]
    ],
    dragonStart: ["A diseased dragon crashes through the ruined gate.", "Ser Kael steps between you and death."],
    kaelDamage: "Ser Kael damages the Diseased Dragon for",
    dragonDamage: "The Diseased Dragon hits Ser Kael for",
    wakeStory: [
      "You wake in a shelter under Ashen Keep. The healer says Kael is gone.",
      "The dragon did not kill you, but it marked your life. Cinderhook Slum becomes your first refuge, your first debt, and the beginning of your climb."
    ]
  },
  es: {
    gameTitle: "Beneath the Throne",
    startSubtitle: "Entra en un reino en ruinas entre ceniza, niebla y el camino hacia Ashen Keep.",
    startNote: "Nueva Partida empieza con un tutorial cinematografico, el evento del dragon/Ser Kael y despues la seleccion de clase.",
    heroName: "Nombre del héroe",
    newGame: "Nueva Partida",
    loadGame: "Cargar Partida",
    language: "Idioma",
    english: "English",
    spanish: "Español",
    selected: "Seleccionado",
    tutorialBattle: "Batalla Tutorial",
    tutorialSub: "Aprende combate antes de la caída de Ashen Keep.",
    goal: "Objetivo",
    skeletonGoal: "Derrota al esqueleto. Usa Atacar, Poción y Defender para ver qué hace cada acción.",
    unchosenSurvivor: "Sobreviviente sin senda",
    roadSkeleton: "Esqueleto del camino",
    tutorialEnemy: "Enemigo tutorial",
    attack: "Atacar",
    skills: "Habilidades",
    skill: "Habilidad",
    healthPotion: "Pocion de salud",
    manaPotion: "Pocion de mana",
    potion: "Poción",
    defend: "Defender",
    help: "Ayuda",
    skip: "Saltar",
    mana: "Maná",
    hp: "PV",
    round: "Ronda",
    yourTurn: "turno",
    combatTurnPlayer: "Tu turno.",
    combatTurnResolving: "Resolviendo turnos...",
    combatTarget: "Objetivo",
    townCenter: "Centro del pueblo",
    slumPrologue: "Prólogo del barrio",
    slumPrologueTitle: "Barrio Bajo de Cinderhook",
    slumPrologueDesc: "Gana monedas, construye un nombre, sobrevive a la presión de las bandas y alcanza la puerta del Barrio Inferior.",
    slumPrologueComplete: "La puerta se ha abierto. La subida completa hacia la sociedad del castillo está lista para convertirse en el arco del juego de pago.",
    slumContracts: "Contratos",
    slumTownWork: "Pueblo y trabajo",
    slumShelterAlly: "Refugio y aliada",
    slumGateReady: "Puerta del Barrio Inferior alcanzada",
    slumGateTest: "Probar la puerta del Barrio Inferior",
    slumGateOpened: "abierta",
    slumGateLocked: "cerrada",
    slumGateReadyLabel: "lista",
    slumRecentRumors: "Rumores recientes",
    slumTownContacts: "Contactos y servicios del pueblo",
    slumChapterBoard: "Tablero del Capitulo 1",
    slumContractBoardDesc: "Un trabajo a la vez. Los contratos mueven monedas, reputacion, seguridad, Mira y la puerta del Barrio Inferior.",
    slumContractBoardComplete: "Cinderhook conoce tu nombre. El camino al Barrio Inferior esta abierto mas alla de la puerta.",
    slumContractBossReady: "Jefe listo",
    slumContractNoNew: "Sin contrato nuevo",
    slumContractNoNewGate: "Cumple los requisitos de la puerta o revisa la puerta del Barrio Inferior.",
    slumContractNoNewMira: "Encuentra y recluta a Mira para desbloquear la ruta del jefe del Capitulo 1.",
    contractAccept: "Aceptar",
    contractHold: "Esperar",
    contractDetails: "Detalles",
    contractDone: "hechos",
    contract_ration_marks_name: "Recuperar comida robada",
    contract_ration_marks_desc: "Rastrea sacos de comida perdidos por los callejones del desague antes de que las Ratas del Muelle los revendan.",
    contract_ration_marks_action: "Buscar en desagues",
    contract_ration_marks_tag: "Mercado",
    contract_ration_marks_log: "Recuperas sacos de racion marcados y los devuelves antes de que abra el mercado.",
    contract_forge_scrap_name: "Traer chatarra a Borin",
    contract_forge_scrap_desc: "Trabaja los montones de ceniza para obtener chatarra util y que Borin repare armas sin hacer preguntas.",
    contract_forge_scrap_action: "Recoger chatarra",
    contract_forge_scrap_tag: "Herreria",
    contract_forge_scrap_log: "Llevas chatarra util a Borin. Anota tu nombre en el lado honesto del libro.",
    contract_knife_corner_name: "Despejar Esquina del Cuchillo",
    contract_knife_corner_desc: "Una banda espera cerca del foso de humo. Despejala y la ruta al refugio sera mas segura.",
    contract_knife_corner_action: "Iniciar pelea",
    contract_knife_corner_tag: "Pelea en callejon",
    contract_knife_corner_log: "Esquina del Cuchillo queda vacia. Las puertas se abren un poco mas cuando pasas.",
    contract_dock_rat_ledger_name: "Destruir el libro de las Ratas del Muelle",
    contract_dock_rat_ledger_desc: "Vale sabe donde guardan las Ratas del Muelle la lista de deudas. Quemala antes de que cobren.",
    contract_dock_rat_ledger_action: "Asaltar el libro",
    contract_dock_rat_ledger_tag: "Banda",
    contract_dock_rat_ledger_log: "El libro de deudas de las Ratas del Muelle arde en una estufa de taberna. Varias familias dejan de susurrar tu nombre como advertencia.",
    contract_gate_lieutenant_name: "Derrotar al teniente de la puerta",
    contract_gate_lieutenant_desc: "El teniente de la banda que vende acceso a la puerta ya no se esconde tras los cobradores. Vencelo y el Capitulo 1 tendra un final real.",
    contract_gate_lieutenant_action: "Desafiar al teniente",
    contract_gate_lieutenant_tag: "Jefe de capitulo",
    contract_gate_lieutenant_log: "El teniente de la puerta cae de rodillas. Cinderhook ve abrirse el camino al Barrio Inferior.",
    noClass: "Todavía no elegiste una clase. Derrota primero al esqueleto. Tus verdaderas habilidades despiertan después del evento del dragón.",
    notEnoughMana: "No tienes suficiente maná.",
    noPotions: "No quedan pociones.",
    noManaPotions: "No quedan pociones de mana.",
    manaFull: "El mana ya esta lleno.",
    skeletonHit: "Esqueleto del Camino araña a",
    heroHits: "ataca por",
    heroHealthPotion: "bebe una pocion de salud y restaura",
    heroManaPotion: "bebe una pocion de mana y restaura",
    heroPotion: "bebe una poción y restaura 35 PV.",
    heroDefend: "defiende. El siguiente golpe se reduce.",
    combatBasics: "Conceptos de Combate",
    combatBasicsBody: "El combate es por turnos. Atacar golpea. Defender reduce el siguiente golpe. Pocion cura. Las habilidades de clase llegan despues de Ser Kael. El boton resaltado es la leccion.",
    lessonAttack: "Leccion 1 de 3 — Atacar",
    lessonAttackBody: "Toca Atacar. Primero el acero. Los huesos responderan.",
    lessonDefend: "Leccion 2 de 3 — Defender",
    lessonDefendBody: "Toca Defender. La guardia corta casi a la mitad el siguiente golpe.",
    lessonPotion: "Leccion 3 de 3 — Pocion",
    lessonPotionBody: "Toca Pocion. Curar gasta el turno: el esqueleto igual golpea despues.",
    lessonFinish: "Terminalo",
    lessonFinishBody: "Ataca hasta que caiga. Saltar sigue ahi si ya sabes pelear.",
    lessonWait: "El esqueleto responde...",
    lessonLocked: "Solo el boton encendido funciona. Saltar si ya sabes pelear.",
    firstVictory: "Primera Victoria",
    firstVictoryBody: "El esqueleto se derrumba. El camino queda en silencio, pero Ashen Keep ya arde más adelante.",
    continueKeep: "Continuar bajo el Bastion",
    dragonTitle: "El Dragón en Ashen Keep",
    dragonSub: "Esta no es una pelea normal. Este es el evento que crea a tu personaje.",
    survivor: "Sobreviviente",
    diseasedDragon: "Dragón Enfermo",
    radiantKnight: "Caballero radiante",
    protectedSurvivor: "Sobreviviente protegido",
    dragonPortraitText: "Dragon marcado por la peste",
    barrier: "Barrera",
    nextMoment: "Siguiente Momento",
    wakeKeep: "Despertar bajo el Bastion",
    ashenKeep: "Ashen Keep",
    chooseClass: "Elegir Clase",
    choosePath: "Elige Tu Camino",
    pathSub: "El ataque del dragón te deja apenas con vida. Un campeón caído te protege lo suficiente para despertar tu primera clase.",
    pathNote: "Cada clase cambia tus estadísticas iniciales, habilidades y el ritmo de tus primeras peleas.",
    choose: "Elegir",
    classNames: {
      warrior: "Guerrero",
      rogue: "Picaro",
      mage: "Mago",
      ranger: "Explorador",
      cleric: "Clerigo"
    },
    classFlavor: {
      warrior: "Una senda de primera linea que convierte el dolor en presion y sostiene el camino cuando otros caen.",
      rogue: "Una hoja en el humo, hecha para velocidad, aperturas sucias y castigos antes de que el enemigo responda.",
      mage: "Un erudito marcado por fuego y fuerza arcana, fragil hasta que el campo se vuelve circulo ritual.",
      ranger: "Un cazador de caminos que lee rastros, controla distancia y sobrevive donde los mapas dejan de mentir.",
      cleric: "Un guardian de juramentos y amparos que lleva luz sanadora por ruinas que quieren apagarla."
    },
    mainTutorialTitle: "Como funciona Cinderhook",
    mainTutorialLead: "Este barrio es el primer peldaño. Hazlo en este orden: los botones usan estos nombres.",
    mainTutorialStep1: "Contratos — acepta Recuperar comida robada y pelea en los callejones.",
    mainTutorialStep2: "Pueblo y trabajo — suministros, forja, descanso y rumores.",
    mainTutorialStep3: "Refugio y aliada — Mira espera aqui. Llevala cuando puedas.",
    mainTutorialStep4: "Acercate a la puerta del Barrio Inferior cuando tengas oro, reputacion y seguridad.",
    mainTutorialStep5: "El Mapa (barra inferior) sale de Cinderhook cuando la puerta abre.",
    mainTutorialStep6: "El icono de balanza es el Libro de la Corte. Vende apariencia, no poder.",
    close: "Cerrar",
    mute: "Silenciar",
    unmute: "Sonido",
    music: "Musica",
    soundFx: "Sonidos de pelea",
    audioOn: "Si",
    audioOff: "No",
    save: "Guardar",
    load: "Cargar",
    emptySlot: "Ranura Vacía",
    damagedSave: "Partida Dañada",
    noSave: "No hay partida guardada en esa ranura.",
    home: "Hogar",
    town: "Ciudad",
    gear: "Equipo",
    party: "Grupo",
    companion: "Companero",
    stats: "Estadisticas",
    classes: "Clases",
    weapons: "Armas",
    mastery: "Maestria",
    abilityBook: "Libro de habilidades",
    knownAbilities: "Habilidades conocidas",
    activeAbilitySlots: "Ranuras de habilidad activas",
    activeInCombat: "Solo las habilidades activas aparecen en combate.",
    slot: "Ranura",
    equip: "Equipar",
    unequip: "Quitar",
    active: "Activa",
    emptyAbilitySlot: "Ranura de habilidad vacia.",
    noActiveAbilities: "No hay habilidades activas equipadas.",
    abilityNotActive: "Esa habilidad no esta equipada.",
    abilityCost: "Costo de mana",
    abilityMilestone: "Hito de habilidad",
    chooseNewAbility: "Elige una nueva habilidad para tu libro.",
    learnAbility: "Aprender",
    learnedAbility: "Habilidad aprendida",
    currentClass: "Clase actual",
    activeClass: "Activa",
    baseClass: "Clase base",
    classPath: "Camino de clase",
    classPaths: "Caminos de clase",
    baseClassPathBody: "Tu entrenamiento original sigue disponible.",
    unlockClass: "Desbloquear clase",
    switchClass: "Cambiar clase",
    classUnlocked: "Clase desbloqueada",
    classChanged: "Clase cambiada",
    unlocked: "Desbloqueada",
    locked: "Bloqueada",
    available: "Disponible",
    requiresLevel: "Requiere nivel",
    weaponMastery: "Maestria de arma",
    spellMastery: "Maestria de hechizos",
    currentWeapon: "Arma actual",
    weaponType: "Tipo de arma",
    critBonus: "Critico",
    damageBonus: "Dano",
    spellDamage: "Hechizo",
    healingBonus: "Sanacion",
    classMastery: "Maestria de clase",
    cmAllocation: "Asignacion de XP a maestria",
    cmAllocationHelp: "Elige cuanta XP de batalla se convierte en XP de maestria en lugar de XP normal.",
    cmXp: "XP de maestria",
    cmPoints: "Puntos de maestria",
    cmSpent: "Maestria gastada",
    cmNextPoint: "Siguiente punto",
    cmAvailable: "Disponible",
    cmPurchased: "Comprada",
    cmLocked: "Bloqueada",
    cmCost: "Costo",
    cmRequires: "Requiere",
    cmRequiresLevel: "Requiere nivel",
    cmRequiresSpent: "Requiere maestria gastada",
    cmRequiresNode: "Requiere maestria",
    cmNoNodes: "No hay nodos de maestria para esta clase.",
    cmBranches: {
      Vanguard: "Vanguardia",
      Breaker: "Rompedor",
      Bulwark: "Baluarte",
      Knives: "Cuchillas",
      Shadows: "Sombras",
      Arcane: "Arcano",
      Elemental: "Elemental",
      Marksman: "Tirador",
      Wilds: "Tierras salvajes",
      Restoration: "Restauracion",
      Warding: "Amparo",
      Judgment: "Juicio",
      Path: "Camino",
      Signature: "Firma",
      Capstone: "Cumbre"
    },
    cmNotEnoughPoints: "Necesitas mas puntos de maestria.",
    cmMasteryBought: "Maestria aprendida",
    normalXp: "XP normal",
    classMasteryXp: "XP de maestria",
    xpSplit: "Division de XP",
    boughtStatus: "Comprada",
    progression: "Progresión",
    map: "Mapa",
    kingdoms: "Reinos",
    currentLocation: "Lugar actual",
    openMap: "Abrir mapa",
    overworldMap: "Mapa del mundo",
    overworldHelp: "Toca un lugar para inspeccionarlo. Los anillos dorados son caminos que puedes tomar. Luego pulsa Viajar.",
    mapActivity: "Actividad del mapa",
    mapEntityCaravan: "Caravana mercante",
    mapEntityPatrol: "Patrulla del camino",
    mapEntityMonster: "Monstruo errante",
    mapEntityAdventurer: "Aventurero errante",
    mapEventCampfire: "Fogata",
    mapEventCrashedCaravan: "Caravana destruida",
    mapEventStrangeGlow: "Brillo magico extrano",
    mapEventBurningVillage: "Marca de aldea en llamas",
    mapEventMonsterNest: "Nido de monstruos",
    mapEventTravelingMerchant: "Mercader viajero",
    playerMarker: "Marcador del jugador",
    travelingTo: "Viajando a",
    travelInProgress: "Viaje en curso",
    travelAmbush: "Emboscada!",
    travelAmbushBody: "Algo se mueve entre la ceniza...",
    travelStrangeEvent: "Senal extrana del camino",
    travelStrangeEventBody: "El camino se curva entre humo viejo y susurros antes de calmarse.",
    travelMerchantEvent: "Mercader del camino",
    travelMerchantEventBody: "Un viajero cauteloso comparte provisiones antes de perderse en la ceniza.",
    travelDiscoveryEvent: "Descubrimiento del camino",
    travelDiscoveryEventBody: "Encuentras un alijo medio enterrado junto al camino.",
    travelRoadStop: "Parada del camino",
    currentRoadStop: "Parada actual del camino",
    destination: "Destino",
    journeyProgress: "Progreso del viaje",
    roadCondition: "Estado del camino",
    roadConditionUncertain: "Incierto",
    roadStopDefaultDesc: "El camino se calma por un momento, aunque la ceniza nunca se asienta del todo.",
    continueJourney: "Continuar viaje",
    inspectArea: "Inspeccionar area",
    turnBack: "Regresar",
    turnBackDisabled: "Regresar solo esta disponible en paradas tras dejar el origen.",
    journeyNotReady: "No estas detenido en el camino.",
    roadStopAlreadyInspected: "Ya registraste esta parada.",
    roadStopInspectFound: "Descubres un pequeno alijo junto al camino.",
    roadStopInspectQuiet: "Encuentras huellas y ceniza fria, pero nada util.",
    roadStopAfterBattle: "El camino vuelve a ser tuyo. La ceniza cae sobre los derrotados.",
    forceTravelEncounterReady: "El siguiente tramo de viaje forzara un encuentro.",
    travelingBetweenRoadStops: "Viajando entre paradas del camino.",
    noServicesOnRoad: "No hay servicios disponibles en este camino.",
    establishCamp: "Establecer campamento",
    campEstablished: "Campamento establecido",
    campAlreadyEstablished: "Ya hay un campamento aqui",
    campActiveSummary: "Tu campamento esta listo en esta parada. Descansa con seguridad entre viajes.",
    fortifyCamp: "Fortificar campamento",
    campFortified: "Campamento fortificado",
    campFortifiedSummary: "Tu campamento fortificado controla el camino. Las emboscadas son menos probables aqui.",
    campAlreadyFortified: "El campamento ya esta fortificado.",
    notEnoughOre: "No hay suficiente mineral.",
    notEnoughGold: "No hay suficiente oro.",
    notEnoughFood: "No hay suficiente comida.",
    futureSystem: "Sistema futuro",
    cannotBuildHere: "No se puede construir aqui",
    controlledTerritory: "Territorio controlado",
    dangerousRoad: "Camino peligroso",
    tooCloseToTown: "Demasiado cerca de los muros del pueblo",
    nearbyThreats: "Amenazas cercanas",
    strategicValue: "Valor estrategico",
    cancelTravel: "Cancelar viaje",
    alreadyTraveling: "Ya estas viajando.",
    travelCanceled: "Viaje cancelado.",
    enterLocation: "Lugar",
    routes: "Rutas",
    localActions: "Acciones locales",
    localActionsHelp: "Rastrea para hallazgos pequenos o caza cuando quieras una batalla cercana.",
    services: "Servicios",
    locationServices: "Servicios del lugar",
    noServicesHere: "No hay servicios disponibles aqui.",
    serviceUnavailable: "Ese servicio no esta disponible en este lugar.",
    travelTo: "Viajar a",
    returnTo: "Volver a",
    backToLocation: "Volver al lugar",
    huntNearby: "Cazar cerca",
    scoutNearby: "Rastrear cerca",
    hardAreas: "Zonas dificiles",
    hardAreasHelp: "Peleas de alto riesgo con grupos enemigos mas fuertes y mejores recompensas. Sirven para probar builds, companeros, pociones y maestria de clase.",
    enterHardArea: "Entrar a zona dificil",
    hardAreaLocked: "Esa zona dificil no esta disponible desde aqui.",
    hardAreaStarted: "Zona dificil iniciada",
    hardAreaCleared: "Zona dificil superada",
    recommendedLevel: "Nivel recomendado",
    enemyCount: "Enemigos",
    highRisk: "Alto riesgo",
    cleared: "Superada",
    attempts: "Intentos",
    danger: "Peligro",
    unknownLocation: "Lugar desconocido.",
    routeLocked: "No hay ruta desde aqui.",
    connectedRoutes: "Rutas conectadas",
    travelFromMapHelp: "Toca un lugar en el mapa o una ruta abajo, y luego viaja.",
    youAreHere: "Estas aqui",
    selectedPlace: "Seleccionado",
    tapPlaceToInspect: "Toca un lugar. El oro es un camino abierto.",
    noRoadFromHere: "No hay camino desde tu campamento actual.",
    roadOpen: "Hay un camino abierto desde donde estas.",
    travelInProgress: "En el camino",
    distantPlaceHint: "No hay camino directo desde aqui. Viaja primero a un lugar conectado.",
    roadsFromHere: "Caminos desde aqui",
    mapZoom: "Zoom del mapa",
    mapZoomIn: "Acercar",
    mapZoomOut: "Alejar",
    mapRecenter: "Centrar en ti",
    mapYou: "Tu",
    mapKey: "Clave del mapa",
    legendYou: "Tu",
    legendOpenRoad: "Camino abierto",
    legendLocked: "Bloqueado",
    statusHere: "Aqui",
    statusOpen: "Abierto",
    statusLocked: "Bloqueado",
    statusFar: "Lejos",
    courtLedger: "Libro de la corte",
    courtLedgerTitle: "Libro de Ash Court",
    courtLedgerBody: "Apariencia, titulo de fundador, camas de guardado extra y pregonero opcional. El poder de combate se gana.",
    noPayToWin: "Sin pagar para ganar",
    cosmeticsFirst: "Apariencia primero",
    adsOptional: "Anuncios opcionales",
    adsRemoved: "Pregonero silenciado",
    wearingTitle: "Llevas",
    offerTagOnce: "Una vez",
    offerTagConvenience: "Camas",
    offerTagLooks: "Apariencia",
    offerTagTip: "Propina",
    offerFounderName: "Edicto de fundador",
    offerFounderDesc: "El primer don justo: titulo, marco de bronce, manto de embers, camas extra y un HUD silencioso.",
    offerFounderTitle: "Titulo de fundador",
    offerFounderFrame: "Marco de bronce",
    offerFounderCloak: "Manto de embers",
    offerFounderAds: "Silenciar al pregonero",
    offerPassName: "Pase de Ash Court",
    offerPassDesc: "Dos camas de guardado extra y un estandarte. Nada que gane una pelea.",
    offerPassSlots: "Camas 4 y 5",
    offerPassBanner: "Estandarte del bastion",
    offerPassAds: "Silenciar al pregonero",
    offerCloakName: "Manto de embers",
    offerCloakDesc: "Un brillo rojo en el retrato. Las estadisticas no cambian.",
    offerCloakLook: "Brillo de manto",
    offerFrameName: "Marco del bastion",
    offerFrameDesc: "Un anillo de oro alrededor del retrato.",
    offerFrameLook: "Anillo del bastion",
    offerPatronName: "Patron de la ceniza",
    offerPatronDesc: "Una propina sin extras, solo un titulo. Ayuda a mantener el mundo pintado.",
    offerPatronTitle: "Titulo de patron",
    owned: "Tuyo",
    buyFor: "Comprar",
    whatsInside: "Que incluye",
    price: "Precio",
    alreadyOwned: "Ya tienes ese edicto.",
    offerMissing: "Esa oferta no esta.",
    checkoutMockBody: "Pago de prueba: no se cobra tarjeta. Se otorga en esta partida para probar la tienda.",
    checkoutOpensTab: "Se abre una pestana si pegaste un enlace de Stripe. Esta partida igual otorga las apariencias.",
    openCheckout: "Abrir pago",
    payPlaytest: "Pagar (prueba)",
    purchaseGranted: "El edicto queda sellado en esta partida.",
    ledgerTitle: "Cobrado",
    ledgerTaken: "Cobrado",
    ledgerEmpty: "Aun no hay edictos sellados.",
    ledgerMockNote: "totales de prueba hasta que pongas enlaces de Stripe",
    crierTitle: "Pregonero",
    crierBody: "Una vez al dia, mira un pregon corto y toma un saquito. Nunca en combate. Nunca obligatorio.",
    watchCrier: "Ver al pregonero",
    crierDoneToday: "El pregonero ya te pago hoy",
    crierGone: "Silenciaste al pregonero. No hay mas saquito de anuncio.",
    crierWatching: "El pregonero habla",
    crierWatchBody: "Sustituto corto de un anuncio recompensado. Oro y comida llegan al terminar.",
    crierPaid: "El pregonero paga",
    realMoneyHow: "Como cobra dinero real",
    realMoneyBody: "Pega enlaces de Stripe en localStorage, clave btt_checkout_urls, JSON con una URL por id. Luego App Store y Play. Ko-fi o Patreon pueden mapear a Patron de la ceniza.",
    realMoneyStripe: "Enlaces de Stripe",
    realMoneyStores: "App Store / Play despues",
    realMoneyTips: "Propinas Ko-fi / Patreon",
    noPowerSales: "Clases, companeros y poder se siguen ganando en el mundo.",
    noPreviousLocation: "No hay lugar anterior.",
    travelEncounter: "Encuentro en el camino",
    travelResource: "Hallazgo de viaje",
    arrivedAt: "Llegaste a",
    scoutEncounter: "Encuentro de exploracion",
    scoutFind: "Hallazgo de exploracion",
    worldMap: "Rutas del mundo",
    worldMapBody: "Usa el mapa para rutas del mundo, lugares conectados y viaje guiado. Los edificios y acciones locales viven en la pantalla del lugar actual.",
    kingdomWorldBody: "La presion de los reinos aun se registra por region. Mas adelante las guerras y asentamientos se uniran a nodos concretos.",
    kingdomLocation: "Base regional",
    combat: "Combate",
    enemies: "Enemigos",
    battleLog: "Registro de batalla",
    nextUp: "Siguiente",
    turnOrder: "Orden de turnos",
    explore: "Explorar",
    hunt: "Cacería Peligrosa",
    boss: "Jefe Regional",
    rest: "Descansar",
    camp: "Acampar",
    run: "Huir",
    auto: "Auto",
    victory: "Recompensas de Victoria",
    defeat: "Derrota",
    defeatBody: "Te arrastran a un lugar seguro y pierdes algo de oro.",
    continue: "Continuar",
    miss: "Falla",
    gold: "Oro",
    food: "Comida",
    ore: "Mineral",
    healthPotions: "Pociones de salud",
    manaPotions: "Pociones de mana",
    resources: "Recursos",
    inn: "Posada",
    market: "Mercado",
    blacksmith: "Herreria",
    tavern: "Taberna",
    mine: "Mina",
    backpack: "Mochila",
    equipped: "Equipado",
    empty: "Vacio",
    characterAppearance: "Apariencia del personaje",
    equipBest: "Equipar mejor",
    sellWorse: "Vender peores",
    sellAllUnequipped: "Vender no equipado",
    sell: "Vender",
    attackShort: "Atq",
    defenseShort: "Def",
    quality_poor: "Pobre",
    quality_common: "Comun",
    quality_fine: "Fino",
    quality_rare: "Raro",
    quality_effect: "Efecto",
    buy: "Comprar",
    hire: "Contratar",
    reroll: "Renovar",
    upgrade: "Mejorar",
    basicSupplies: "Suministros basicos",
    basicGear: "Equipo basico",
    buyHealthPotion: "Comprar pocion de salud",
    buyManaPotion: "Comprar pocion de mana",
    buyFood: "Comprar comida",
    marketRefresh: "El inventario se renueva cada dia. Renovar cuesta oro.",
    tavernRefresh: "Los reclutas se renuevan cada dia. Renovar cuesta oro.",
    upkeep: "Mantenimiento",
    activeCompanions: "Companeros activos",
    monthlyWages: "Salarios mensuales",
    dailyFoodNeed: "Comida diaria",
    noCompanions: "Aun no has contratado companeros.",
    noCompanionsHelp: "Recluta companeros en tabernas o encuentra aliados con nombre durante eventos de historia.",
    companionSystemHelp: "Elige quien pelea, cambia tacticas, entrena companeros y sube vinculo en batallas activas.",
    companionBook: "Libro",
    role: "Rol",
    tactic: "Tactica",
    bond: "Vinculo",
    bondGrew: "El vinculo crecio",
    training: "Entrenamiento",
    train: "Entrenar",
    trained: "Entrenado",
    bench: "Reservar",
    benched: "Reserva",
    activate: "Activar",
    speed: "Velocidad",
    loyalty: "Lealtad",
    morale: "Moral",
    partyFull: "Grupo lleno",
    partyFullBody: "Reserva otro companero antes de activar este.",
    noGearEquipped: "No hay objeto equipado.",
    upgradeCost: "Siguiente mejora",
    fullyUpgraded: "Mejora maxima.",
    upgraded: "Mejorado",
    mineForOre: "Extraer mineral",
    mineResult: "Resultados de la mina",
    mineBody: "Pasa 5 dias reuniendo mineral para mejoras de herreria.",
    mineGathered: "Reuniste mineral durante 5 dias.",
    needGold: "Necesitas mas oro.",
    needOre: "Necesitas mas mineral.",
    needFood: "Necesitas mas comida.",
    bought: "Comprado",
    hired: "Contratado",
    stockRefreshesDaily: "Se renueva cada dia",
    day: "Día",
    level: "Nv",
    classStats: {
      strength: "Daño físico y poder con armas pesadas.",
      wisdom: "Magia, sanación y habilidades de maná.",
      endurance: "PV máximos y supervivencia.",
      speed: "Orden de turnos y evasión.",
      luck: "Críticos, botín y oportunidades extrañas."
    },
    statNames: {strength:"Fuerza", wisdom:"Sabiduría", endurance:"Resistencia", speed:"Velocidad", luck:"Suerte"},
    initialStory: [
      "Ser Kael cayó bajo el dragón, pero su barrera te salvó.",
      "Despertaste bajo Ashen Keep con humo en los pulmones, deuda de puerta en tu nombre y un camino de clase ardiendo en tu sangre.",
      "Cinderhook es tu primer refugio. La puerta del Barrio Bajo se ve sobre los techos.",
      "Cada día cuesta comida. Cada decisión cambia moneda, seguridad, reputación y presión de bandas."
    ],
    story: "Historia",
    current: "Actual",
    travel: "Viajar",
    regions: {
      ashen_fields:{name:"Campos de Ceniza",desc:"Caminos quemados, ruinas bajas y las primeras cacerías seguras."},
      green_march:{name:"Marca Verde",desc:"Bandidos, bestias y viejas torres cubiertas por enredaderas."},
      frostmere:{name:"Frostmere",desc:"Lagos congelados y soldados que nunca volvieron a casa."},
      storm_coast:{name:"Costa de Tormentas",desc:"Relámpagos sobre acantilados negros y saqueadores bajo velas rotas."},
      hollow_kingdom:{name:"Reino Hueco",desc:"Banderas muertas aún ondean sobre caminos malditos y ciudades antiguas."}
    },
    dragonMoments: [
      ["Guardia Radiante", "Ser Kael clava su espada en la piedra. Un escudo de oro pálido te rodea.", 0, 0],
      ["Cruce de Espadas", "Kael avanza. Dos arcos de espada cortan el pecho del dragón.", 0, 620],
      ["Fuego del Dragón", "El dragón exhala fuego negro. Kael mantiene la línea, pero su armadura empieza a brillar roja.", 720, 0],
      ["Última Espada", "Kael salta entre el humo y hunde su espada bajo la mandíbula del dragón.", 0, 870],
      ["El Aplastamiento", "El dragón atrapa a Kael con sus garras. El viejo caballero mira una vez más para asegurar que la barrera aguante.", 2600, 0]
    ],
    dragonStart: ["Un dragón enfermo atraviesa la puerta destruida.", "Ser Kael se interpone entre tú y la muerte."],
    kaelDamage: "Ser Kael daña al Dragón Enfermo por",
    dragonDamage: "El Dragón Enfermo golpea a Ser Kael por",
    wakeStory: [
      "Despiertas en un refugio bajo Ashen Keep. La sanadora dice que Kael ha muerto.",
      "El dragon no te mato, pero marco tu vida. Cinderhook sera tu primer refugio, tu primera deuda y el inicio de tu ascenso."
    ]
  }
};

let currentLanguage = loadLanguage();

function loadLanguage(){
  try{return localStorage.getItem(LANGUAGE_KEY)==="es"?"es":"en";}catch(e){return"en";}
}

export function setLanguage(lang){
  currentLanguage = lang==="es" ? "es" : "en";
  try{localStorage.setItem(LANGUAGE_KEY,currentLanguage);}catch(e){}
  document.documentElement.lang = currentLanguage;
}

export function getLanguage(){
  return currentLanguage;
}

export function dictionary(){
  return TEXT[currentLanguage] || TEXT.en;
}

export function tx(key){
  return dictionary()[key] ?? TEXT.en[key] ?? key;
}

export function title(text){
  return String(text).replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
}

export function statExplanation(stat){
  const stats = dictionary().classStats || TEXT.en.classStats;
  return stats[stat] || stat;
}

export function statName(stat){
  const names = dictionary().statNames || TEXT.en.statNames;
  return names[stat] || title(stat);
}

export function regionText(region, field){
  const regions = dictionary().regions || TEXT.en.regions;
  return regions[region.id]?.[field] || region[field] || region.id;
}
