export const ROAD_STOP_DEFAULT_ART = "assets/ministops/generated/default-road-stop-v18.png";

export const ROAD_NODES = {
  ashen_gate: {
    id: "ashen_gate",
    type: "road",
    danger: 1,
    x: 27.4,
    y: 69.0,
    name: {en: "Ashen Gate", es: "Puerta de Ceniza"},
    desc: {
      en: "The keep's last torches gutter behind you. Tracks split through soot and broken stone.",
      es: "Las ultimas antorchas del bastion tiemblan a tu espalda. Huellas se dividen entre hollin y piedra rota."
    },
    condition: {en: "Guarded ashes", es: "Ceniza vigilada"},
    art: "assets/ministops/generated/ashen-gate-v18.png",
    thumbnail: "assets/ministops/generated/ashen-gate-v18.png",
    sceneClass: "road-stop-art-ash road-stop-art-ember",
    mood: "scorched refuge",
    lighting: "ember",
    buildable: false,
    buildRestrictionReason: "tooCloseToTown",
    controlledBy: "ashen_keep",
    claimCost: null,
    roadBuildCost: null,
    allowedStructures: [],
    nearbyThreats: ["raiders"],
    canBeAttacked: false,
    strategicValue: 2
  },
  broken_road: {
    id: "broken_road",
    type: "road",
    danger: 1,
    x: 33.4,
    y: 61.5,
    name: {en: "Broken Road", es: "Camino Roto"},
    desc: {
      en: "Split flagstones sink into old mud. Someone dragged a cart this way recently.",
      es: "Losas partidas se hunden en barro viejo. Alguien arrastro una carreta por aqui hace poco."
    },
    condition: {en: "Cracked road", es: "Camino agrietado"},
    art: "assets/ministops/generated/broken-road-v18.png",
    thumbnail: "assets/ministops/generated/broken-road-v18.png",
    sceneClass: "road-stop-art-road road-stop-art-ash",
    mood: "exposed road",
    lighting: "overcast",
    buildable: true,
    buildRestrictionReason: "",
    controlledBy: null,
    claimCost: {gold: 45, food: 2},
    roadBuildCost: {gold: 30, ore: 2},
    allowedStructures: ["camp", "watchpost", "roadworks"],
    nearbyThreats: ["bandits"],
    canBeAttacked: true,
    strategicValue: 3
  },
  ruined_waystone: {
    id: "ruined_waystone",
    type: "road",
    danger: 2,
    x: 31.5,
    y: 51.5,
    name: {en: "Ruined Waystone", es: "Piedra Guia en Ruinas"},
    desc: {
      en: "A scorched milestone leans beside the road. Its carved names have been clawed away.",
      es: "Un hito quemado se inclina junto al camino. Sus nombres tallados fueron arrancados a zarpazos."
    },
    condition: {en: "Uncertain marker", es: "Marca incierta"},
    art: "assets/ministops/generated/ruined-waystone-v18.png",
    thumbnail: "assets/ministops/generated/ruined-waystone-v18.png",
    sceneClass: "road-stop-art-road road-stop-art-strange",
    mood: "lonely marker",
    lighting: "sickly glow",
    buildable: true,
    buildRestrictionReason: "",
    controlledBy: null,
    claimCost: {gold: 55, ore: 1},
    roadBuildCost: {gold: 35, ore: 3},
    allowedStructures: ["camp", "waystone", "trade_post"],
    nearbyThreats: ["undead", "scavengers"],
    canBeAttacked: true,
    strategicValue: 3
  },
  burned_shrine: {
    id: "burned_shrine",
    type: "road",
    danger: 2,
    x: 29.0,
    y: 45.0,
    name: {en: "Burned Shrine", es: "Santuario Quemado"},
    desc: {
      en: "Blackened prayer stones circle a cold altar. The ash here still smells of oil.",
      es: "Piedras de plegaria ennegrecidas rodean un altar frio. La ceniza aqui aun huele a aceite."
    },
    condition: {en: "Cursed soot", es: "Hollin maldito"},
    art: "assets/ministops/generated/burned-shrine-v18.png",
    thumbnail: "assets/ministops/generated/burned-shrine-v18.png",
    sceneClass: "road-stop-art-ash road-stop-art-ember",
    mood: "cursed shrine",
    lighting: "eerie ember",
    buildable: true,
    buildRestrictionReason: "",
    controlledBy: null,
    claimCost: {gold: 65, ore: 2},
    roadBuildCost: {gold: 45, ore: 4},
    allowedStructures: ["hidden_camp", "ward_post"],
    nearbyThreats: ["cultists", "undead"],
    canBeAttacked: true,
    strategicValue: 4
  },
  ashen_slope: {
    id: "ashen_slope",
    type: "road",
    danger: 3,
    x: 42.5,
    y: 41.5,
    name: {en: "Ashen Slope", es: "Ladera de Ceniza"},
    desc: {
      en: "The road climbs through gray grass and brittle fence posts. The wind carries faint whispers.",
      es: "El camino sube entre hierba gris y postes quebradizos. El viento trae susurros lejanos."
    },
    condition: {en: "Exposed slope", es: "Ladera expuesta"},
    art: "assets/ministops/generated/ashen-slope-v18.png",
    thumbnail: "assets/ministops/generated/ashen-slope-v18.png",
    sceneClass: "road-stop-art-slope road-stop-art-wind",
    mood: "wind exposed",
    lighting: "cold gray",
    buildable: true,
    buildRestrictionReason: "",
    controlledBy: null,
    claimCost: {gold: 70, food: 2},
    roadBuildCost: {gold: 50, ore: 4},
    allowedStructures: ["watchpost", "signal_fire"],
    nearbyThreats: ["ash_wolves", "raiders"],
    canBeAttacked: true,
    strategicValue: 4
  },
  watchtower_approach: {
    id: "watchtower_approach",
    type: "road",
    danger: 4,
    x: 50.3,
    y: 28.8,
    name: {en: "Watchtower Approach", es: "Acceso a la Torre"},
    desc: {
      en: "Broken arches frame the tower path. Every sound seems to climb ahead of you.",
      es: "Arcos rotos enmarcan el sendero de la torre. Cada sonido parece subir delante de ti."
    },
    condition: {en: "Watched ruins", es: "Ruinas vigiladas"},
    art: "assets/ministops/generated/watchtower-approach-v18.png",
    thumbnail: "assets/ministops/generated/watchtower-approach-v18.png",
    sceneClass: "road-stop-art-ridge road-stop-art-wind",
    mood: "watched approach",
    lighting: "cold ridge",
    buildable: false,
    buildRestrictionReason: "dangerousRoad",
    controlledBy: "ruined_watchtower",
    claimCost: {gold: 90, ore: 5},
    roadBuildCost: {gold: 80, ore: 6},
    allowedStructures: ["watchpost", "ward_post"],
    nearbyThreats: ["cursed_knights", "cultists"],
    canBeAttacked: true,
    strategicValue: 5
  },
  old_crossroads: {
    id: "old_crossroads",
    type: "road",
    danger: 2,
    x: 47.1,
    y: 55.7,
    name: {en: "Old Crossroads", es: "Viejo Cruce"},
    desc: {
      en: "Three roads meet around a cracked post. Fresh bootprints vanish under drifting dust.",
      es: "Tres caminos se unen alrededor de un poste roto. Huellas recientes desaparecen bajo polvo errante."
    },
    condition: {en: "Busy crossing", es: "Cruce transitado"},
    art: "assets/ministops/generated/old-crossroads-v18.png",
    thumbnail: "assets/ministops/generated/old-crossroads-v18.png",
    sceneClass: "road-stop-art-road road-stop-art-crossroads",
    mood: "worn crossing",
    lighting: "low dusk",
    buildable: true,
    buildRestrictionReason: "",
    controlledBy: null,
    claimCost: {gold: 85, food: 3},
    roadBuildCost: {gold: 65, ore: 4},
    allowedStructures: ["camp", "trade_post", "roadworks"],
    nearbyThreats: ["bandits", "monsters"],
    canBeAttacked: true,
    strategicValue: 5
  },
  abandoned_cart: {
    id: "abandoned_cart",
    type: "road",
    danger: 2,
    x: 42.0,
    y: 58.2,
    name: {en: "Abandoned Cart", es: "Carreta Abandonada"},
    desc: {
      en: "A broken cart blocks part of the road. Its cargo was taken, but not cleanly.",
      es: "Una carreta rota bloquea parte del camino. Su carga fue tomada, pero no limpiamente."
    },
    condition: {en: "Blocked ruts", es: "Surcos bloqueados"},
    art: "assets/ministops/generated/abandoned-cart-v18.png",
    thumbnail: "assets/ministops/generated/abandoned-cart-v18.png",
    sceneClass: "road-stop-art-road road-stop-art-ash",
    mood: "raided roadside",
    lighting: "dusty dusk",
    buildable: true,
    buildRestrictionReason: "",
    controlledBy: null,
    claimCost: {gold: 50, food: 1},
    roadBuildCost: {gold: 35, ore: 2},
    allowedStructures: ["camp", "salvage_post"],
    nearbyThreats: ["bandits"],
    canBeAttacked: true,
    strategicValue: 3
  },
  traveler_camp: {
    id: "traveler_camp",
    type: "road",
    danger: 1,
    x: 63.5,
    y: 61.5,
    name: {en: "Traveler Camp", es: "Campamento de Viajeros"},
    desc: {
      en: "A ring of stones marks a careful camp. The embers are buried, but still warm.",
      es: "Un aro de piedras marca un campamento prudente. Las brasas estan cubiertas, pero tibias."
    },
    condition: {en: "Recent camp", es: "Campamento reciente"},
    art: "assets/ministops/generated/traveler-camp-v18.png",
    thumbnail: "assets/ministops/generated/traveler-camp-v18.png",
    sceneClass: "road-stop-art-camp road-stop-art-warm",
    mood: "temporary shelter",
    lighting: "campfire",
    buildable: true,
    buildRestrictionReason: "",
    controlledBy: null,
    claimCost: {gold: 60, food: 3},
    roadBuildCost: {gold: 40, ore: 2},
    allowedStructures: ["camp", "trade_post"],
    nearbyThreats: ["thieves"],
    canBeAttacked: true,
    strategicValue: 3
  },
  market_outskirts: {
    id: "market_outskirts",
    type: "road",
    danger: 1,
    x: 74.8,
    y: 68.0,
    name: {en: "Market Outskirts", es: "Afueras del Mercado"},
    desc: {
      en: "Lantern smoke shows through the haze. The town guards are near, but not near enough.",
      es: "Humo de faroles aparece entre la bruma. Los guardias del pueblo estan cerca, pero no tanto."
    },
    condition: {en: "Safer road", es: "Camino mas seguro"},
    art: "assets/ministops/generated/market-outskirts-v18.png",
    thumbnail: "assets/ministops/generated/market-outskirts-v18.png",
    sceneClass: "road-stop-art-town road-stop-art-warm",
    mood: "guarded road",
    lighting: "lantern",
    buildable: false,
    buildRestrictionReason: "controlledTerritory",
    controlledBy: "market_town",
    claimCost: null,
    roadBuildCost: {gold: 25, ore: 1},
    allowedStructures: ["trade_post"],
    nearbyThreats: ["toll_guards"],
    canBeAttacked: false,
    strategicValue: 2
  },
  forest_trail: {
    id: "forest_trail",
    type: "road",
    danger: 3,
    x: 69.5,
    y: 39.5,
    name: {en: "Forest Trail", es: "Sendero del Bosque"},
    desc: {
      en: "Roots break through the road. The forest swallows torchlight before it reaches the branches.",
      es: "Raices rompen el camino. El bosque traga la luz antes de que alcance las ramas."
    },
    condition: {en: "Tangled trail", es: "Sendero enredado"},
    art: "assets/ministops/generated/forest-trail-v18.png",
    thumbnail: "assets/ministops/generated/forest-trail-v18.png",
    sceneClass: "road-stop-art-forest road-stop-art-fog",
    mood: "dark woodland",
    lighting: "blue shadow",
    buildable: true,
    buildRestrictionReason: "",
    controlledBy: null,
    claimCost: {gold: 80, food: 4},
    roadBuildCost: {gold: 60, ore: 5},
    allowedStructures: ["hidden_camp", "watchpost"],
    nearbyThreats: ["wolves", "cultists"],
    canBeAttacked: true,
    strategicValue: 4
  },
  ridge_path: {
    id: "ridge_path",
    type: "road",
    danger: 3,
    x: 61.8,
    y: 25.0,
    name: {en: "Ridge Path", es: "Camino de la Cresta"},
    desc: {
      en: "The ridge narrows into loose stone. Below, the fields vanish behind ash and fog.",
      es: "La cresta se estrecha en piedra suelta. Abajo, los campos desaparecen tras ceniza y niebla."
    },
    condition: {en: "Narrow ridge", es: "Cresta estrecha"},
    art: "assets/ministops/generated/ridge-path-v18.png",
    thumbnail: "assets/ministops/generated/ridge-path-v18.png",
    sceneClass: "road-stop-art-ridge road-stop-art-wind",
    mood: "high ridge",
    lighting: "moonlit cold",
    buildable: true,
    buildRestrictionReason: "",
    controlledBy: null,
    claimCost: {gold: 90, food: 2, ore: 2},
    roadBuildCost: {gold: 75, ore: 6},
    allowedStructures: ["watchpost", "signal_fire"],
    nearbyThreats: ["harpies", "raiders"],
    canBeAttacked: true,
    strategicValue: 5
  }
};

export const MAJOR_TRAVEL_ROUTES = {
  ashen_keep__ashen_fields: ["ashen_keep", "ashen_gate", "ruined_waystone", "burned_shrine", "ashen_fields"],
  ashen_keep__old_road: ["ashen_keep", "ashen_gate", "broken_road", "abandoned_cart", "old_crossroads", "old_road"],
  ashen_keep__market_town: ["ashen_keep", "ashen_gate", "broken_road", "abandoned_cart", "old_crossroads", "traveler_camp", "market_outskirts", "market_town"],
  ashen_fields__old_road: ["ashen_fields", "burned_shrine", "ashen_slope", "old_crossroads", "old_road"],
  ashen_fields__ruined_watchtower: ["ashen_fields", "ashen_slope", "watchtower_approach", "ruined_watchtower"],
  old_road__forest_edge: ["old_road", "old_crossroads", "forest_trail", "forest_edge"],
  old_road__market_town: ["old_road", "old_crossroads", "traveler_camp", "market_outskirts", "market_town"],
  forest_edge__ruined_watchtower: ["forest_edge", "forest_trail", "ridge_path", "ruined_watchtower"]
};

export const ROAD_SEGMENT_PATHS = {
  ashen_keep__ashen_gate: [{x: 22.5, y: 77.2}, {x: 24.5, y: 73.8}, {x: 27.4, y: 69.0}],
  ashen_gate__broken_road: [{x: 27.4, y: 69.0}, {x: 29.7, y: 65.6}, {x: 33.4, y: 61.5}],
  ashen_gate__ruined_waystone: [{x: 27.4, y: 69.0}, {x: 28.1, y: 63.2}, {x: 29.0, y: 57.2}, {x: 31.5, y: 51.5}],
  ruined_waystone__burned_shrine: [{x: 31.5, y: 51.5}, {x: 30.2, y: 48.5}, {x: 29.0, y: 45.0}],
  burned_shrine__ashen_fields: [{x: 29.0, y: 45.0}, {x: 29.8, y: 41.6}, {x: 30.0, y: 37.5}],
  burned_shrine__ashen_slope: [{x: 29.0, y: 45.0}, {x: 33.0, y: 43.2}, {x: 38.0, y: 42.5}, {x: 42.5, y: 41.5}],
  ashen_slope__old_crossroads: [{x: 42.5, y: 41.5}, {x: 45.2, y: 47.8}, {x: 47.1, y: 55.7}],
  ashen_slope__watchtower_approach: [{x: 42.5, y: 41.5}, {x: 45.5, y: 35.5}, {x: 50.3, y: 28.8}],
  watchtower_approach__ruined_watchtower: [{x: 50.3, y: 28.8}, {x: 52.0, y: 21.8}, {x: 54.0, y: 15.5}],
  broken_road__abandoned_cart: [{x: 33.4, y: 61.5}, {x: 37.0, y: 59.6}, {x: 42.0, y: 58.2}],
  abandoned_cart__old_crossroads: [{x: 42.0, y: 58.2}, {x: 44.6, y: 57.2}, {x: 47.1, y: 55.7}],
  old_crossroads__old_road: [{x: 47.1, y: 55.7}, {x: 49.2, y: 54.7}, {x: 52.2, y: 54.8}],
  old_crossroads__traveler_camp: [{x: 47.1, y: 55.7}, {x: 54.5, y: 55.8}, {x: 60.0, y: 58.9}, {x: 63.5, y: 61.5}],
  traveler_camp__market_outskirts: [{x: 63.5, y: 61.5}, {x: 69.8, y: 63.2}, {x: 74.8, y: 68.0}],
  market_outskirts__market_town: [{x: 74.8, y: 68.0}, {x: 79.0, y: 71.4}, {x: 82.8, y: 77.4}],
  old_crossroads__forest_trail: [{x: 47.1, y: 55.7}, {x: 55.8, y: 50.6}, {x: 62.0, y: 44.2}, {x: 69.5, y: 39.5}],
  forest_trail__forest_edge: [{x: 69.5, y: 39.5}, {x: 72.5, y: 34.7}, {x: 75.6, y: 31.0}],
  forest_trail__ridge_path: [{x: 69.5, y: 39.5}, {x: 67.2, y: 33.8}, {x: 61.8, y: 25.0}],
  ridge_path__ruined_watchtower: [{x: 61.8, y: 25.0}, {x: 58.0, y: 19.5}, {x: 54.0, y: 15.5}]
};

export function roadKey(a,b){
  return [a,b].sort().join("__");
}

export function getMapNodes(majorLocations = {}){
  return {...ROAD_NODES, ...majorLocations};
}
